/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * SEQ                 | AUTHOR                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 1 | maintainer@emeraldcoastsystemsgroup.com   | Shared, env-driven analytics snippet for every oswarm.ai head builder (theme.js page(), site-lab-report.js, site-apps-catalog.js ANALYTICS marker). Default is NONE: with SITE_ANALYTICS_PROVIDER unset/none the builder returns '' and every generated byte is identical to an analytics-free site, so the tracked pages cannot churn. Misconfiguration (missing token, unknown provider, unsafe value) WARNS to stderr and still returns '' — analytics must never break or block a site build. Values are charset-validated before interpolation so a bad env var cannot inject markup. Config is read from the repo-root .env via dotenv (site-lab-report.js precedent) so all three invocation contexts — deploy script, nightly ps1, manual node run — see one config source. NOTE: adding a third-party script is a deliberate, documented exception to the site's self-contained-pages rule (theme.js SEQ-1); it only happens when the operator opts in via env.
 */
'use strict';

const path = require('path');

// Load the repo-root .env explicitly (not cwd-relative) so generation is deterministic no matter
// which directory the generator is invoked from. dotenv never overrides already-set env vars, and
// a missing .env is fine — the feature just stays off. Fail-soft: analytics must never throw.
try {
  require('dotenv').config({ path: path.resolve(__dirname, '..', '..', '..', '.env'), quiet: true });
} catch (err) {
  process.stderr.write(`[site-analytics] WARN: dotenv unavailable (${err && err.message}) — reading process.env only\n`);
}

/** Charset allowlists: values are interpolated into HTML attributes, so anything outside these
 *  shapes is refused (warn + no analytics) rather than escaped — there is no legitimate beacon
 *  token or hostname that needs quotes or angle brackets. */
const TOKEN_RE = /^[A-Za-z0-9_-]{1,128}$/;
const DOMAIN_RE = /^[A-Za-z0-9.-]{1,253}$/;
const HOST_RE = /^https?:\/\/[A-Za-z0-9.-]{1,253}(?::\d{1,5})?$/;

/** Writes a one-line warning to stderr — never stdout (site-lab-report.js --stdout pipes stdout). */
function warn(message) {
  process.stderr.write(`[site-analytics] WARN: ${message} — emitting no analytics\n`);
}

/**
 * @description Normalizes SITE_ANALYTICS_HOST: trims, strips trailing slashes, and prefixes
 * https:// when no scheme was given, so both "plausible.example.com" and
 * "https://plausible.example.com/" configure the same origin.
 * @param {string} raw - The raw env value (may be empty).
 * @returns {string} A scheme-qualified origin with no trailing slash, or '' when unset.
 */
function normalizeHost(raw) {
  const trimmed = String(raw || '').trim().replace(/\/+$/, '');
  if (!trimmed) return '';
  return /^https?:\/\//i.test(trimmed) ? trimmed : `https://${trimmed}`;
}

/** Cloudflare Web Analytics beacon — needs the site token from the CF dashboard. */
function cloudflareSnippet(token) {
  if (!token) { warn('SITE_ANALYTICS_PROVIDER=cloudflare requires SITE_ANALYTICS_TOKEN (beacon token)'); return ''; }
  if (!TOKEN_RE.test(token)) { warn('SITE_ANALYTICS_TOKEN has characters outside [A-Za-z0-9_-]'); return ''; }
  return `\n<script defer src="https://static.cloudflareinsights.com/beacon.min.js" data-cf-beacon='{"token": "${token}"}'></script>`;
}

/** Plausible script tag — data-domain defaults to oshal.ai, host to plausible.io (self-host via SITE_ANALYTICS_HOST). */
function plausibleSnippet(domain, host) {
  const origin = host || 'https://plausible.io';
  if (!DOMAIN_RE.test(domain)) { warn(`SITE_ANALYTICS_DOMAIN '${domain}' is not a plain hostname`); return ''; }
  if (!HOST_RE.test(origin)) { warn(`SITE_ANALYTICS_HOST '${origin}' is not an http(s) origin`); return ''; }
  return `\n<script defer data-domain="${domain}" src="${origin}/js/script.js"></script>`;
}

/** PostHog loader — fetches the bundle from the configured host and inits with the project key. */
function posthogSnippet(token, host) {
  const origin = host || 'https://us.i.posthog.com';
  if (!token) { warn('SITE_ANALYTICS_PROVIDER=posthog requires SITE_ANALYTICS_TOKEN (project API key)'); return ''; }
  if (!TOKEN_RE.test(token)) { warn('SITE_ANALYTICS_TOKEN has characters outside [A-Za-z0-9_-]'); return ''; }
  if (!HOST_RE.test(origin)) { warn(`SITE_ANALYTICS_HOST '${origin}' is not an http(s) origin`); return ''; }
  return `\n<script>(function(h,k){var d=document,s=d.createElement('script');s.defer=true;s.src=h+'/static/array.js';s.onload=function(){if(window.posthog&&window.posthog.init){window.posthog.init(k,{api_host:h});}};d.head.appendChild(s);})('${origin}','${token}');</script>`;
}

/** Memoized result so ~70 page() calls compute (and warn) exactly once per process. */
let cached = null;

/**
 * @description Builds the site analytics `<script>` snippet from SITE_ANALYTICS_* env vars.
 * Providers: none (default) | cloudflare | plausible | posthog. Returns '' when the provider is
 * none/unset, unknown, or a required value is missing/unsafe — warning to stderr, never throwing —
 * so an unconfigured or misconfigured box always generates a byte-identical analytics-free site.
 * The non-empty result starts with a newline so callers can interpolate it directly before
 * `</head>` without disturbing existing formatting.
 * @returns {string} The snippet HTML, or '' for no analytics.
 */
function analyticsSnippet() {
  if (cached !== null) return cached;
  const provider = String(process.env.SITE_ANALYTICS_PROVIDER || 'none').trim().toLowerCase();
  const token = String(process.env.SITE_ANALYTICS_TOKEN || '').trim();
  const domain = String(process.env.SITE_ANALYTICS_DOMAIN || 'oshal.ai').trim();
  const host = normalizeHost(process.env.SITE_ANALYTICS_HOST);
  if (!provider || provider === 'none') cached = '';
  else if (provider === 'cloudflare') cached = cloudflareSnippet(token);
  else if (provider === 'plausible') cached = plausibleSnippet(domain, host);
  else if (provider === 'posthog') cached = posthogSnippet(token, host);
  else { warn(`unknown SITE_ANALYTICS_PROVIDER '${provider}' (expected none|cloudflare|plausible|posthog)`); cached = ''; }
  return cached;
}

module.exports = { analyticsSnippet };
