/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * SEQ                 | AUTHOR                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 1 | maintainer@emeraldcoastsystemsgroup.com   | Documentation backfill: added file-header change log block and JSDoc on exported members
 */

/**
 * Facebook API Integration Tools
 *
 * Generated by: agent-factory-bot
 * Source ticket: task_d4bea394 (swarm-workspace/task_d4bea394/)
 * Deployed to: server/services/tools/facebook/facebookTools.js
 * Convention: tools/{agent-name}/{agent-name}Tools.js
 *
 * Provides tools for posting, reading, and replying to Facebook content via Graph API.
 * All tools are wrapped in a credential guard — if not connected, they return a
 * structured NOT_CONNECTED error instead of throwing.
 *
 * Required env vars (developer portal constants):
 *   FACEBOOK_APP_ID        — App ID
 *   FACEBOOK_APP_SECRET    — App secret
 *
 * Page token and page ID are managed by the credential store (OAuth flow),
 * NOT environment variables.
 *
 * @module facebookTools
 * @agent facebook-bot
 * @ticket task_d4bea394
 */

const axios = require('axios');
const credentialStore = require('./facebookCredentialStore');

// Configuration
const FACEBOOK_GRAPH_API_VERSION = 'v18.0';
const FACEBOOK_GRAPH_API_BASE = `https://graph.facebook.com/${FACEBOOK_GRAPH_API_VERSION}`;
const MAX_RETRIES = 3;
const INITIAL_BACKOFF_MS = 1000;

/**
 * Rate limiter implementation using token bucket algorithm
 */
class RateLimiter {
  /**
   * @description Initialize the token bucket with a starting balance and refill cadence so callers can self-throttle against Facebook's per-hour API quota before requests are rejected upstream.
   * @param {number} [maxTokens=200] - Maximum tokens the bucket can hold; mirrors Facebook's per-user hourly call ceiling.
   * @param {number} [refillRate=200] - Number of tokens replenished per refill interval.
   * @param {number} [refillIntervalMs=3600000] - Length of the refill window in milliseconds.
   */
  constructor(maxTokens = 200, refillRate = 200, refillIntervalMs = 3600000) {
    this.maxTokens = maxTokens; // Facebook allows ~200 calls per hour per user
    this.tokens = maxTokens;
    this.refillRate = refillRate;
    this.refillIntervalMs = refillIntervalMs;
    this.lastRefill = Date.now();
  }

  /**
   * @description Lazily top up the token balance based on how much time has elapsed, avoiding a background timer so the limiter only does work when a request is actually attempted.
   * @returns {void}
   */
  refill() {
    const now = Date.now();
    const elapsed = now - this.lastRefill;
    const tokensToAdd = Math.floor((elapsed / this.refillIntervalMs) * this.refillRate);
    if (tokensToAdd > 0) {
      this.tokens = Math.min(this.maxTokens, this.tokens + tokensToAdd);
      this.lastRefill = now;
    }
  }

  /**
   * @description Attempt a non-blocking spend of a single token, letting callers fail fast or branch when no quota remains rather than waiting.
   * @returns {boolean} True if a token was available and consumed, false if the bucket is empty.
   */
  tryConsume() {
    this.refill();
    if (this.tokens > 0) {
      this.tokens--;
      return true;
    }
    return false;
  }

  /**
   * @description Block until a token is available so request senders can transparently smooth bursts into Facebook's rate window instead of erroring out.
   * @returns {Promise<void>} Resolves once a token has been consumed.
   */
  async waitForToken() {
    this.refill();
    if (this.tokens > 0) {
      this.tokens--;
      return;
    }
    const waitTime = Math.ceil(this.refillIntervalMs / this.refillRate);
    await new Promise(resolve => setTimeout(resolve, waitTime));
    this.tokens--;
  }
}

// Shared rate limiter instance
const rateLimiter = new RateLimiter();

/**
 * Facebook API client with authentication and rate limiting.
 * Constructed with credentials from the credential store.
 */
class FacebookAPIClient {
  /**
   * @description Assemble a per-call client bound to a specific page's credentials, falling back to app-level env secrets, so each tool invocation talks to Graph API as the connected page.
   * @param {Object} [config={}] - Credential and configuration overrides for this client instance.
   * @param {string} [config.accessToken] - Page or user access token used to authenticate requests.
   * @param {string} [config.appId] - Facebook App ID; defaults to the FACEBOOK_APP_ID env var.
   * @param {string} [config.appSecret] - Facebook App secret; defaults to the FACEBOOK_APP_SECRET env var.
   * @param {string} [config.pageId] - ID of the Facebook page the tools act on.
   */
  constructor(config = {}) {
    this.accessToken = config.accessToken;
    this.appId = config.appId || process.env.FACEBOOK_APP_ID;
    this.appSecret = config.appSecret || process.env.FACEBOOK_APP_SECRET;
    this.pageId = config.pageId;
    this.rateLimiter = rateLimiter;
  }

  /**
   * @description Confirm the stored token is still live and trusted by Facebook before relying on it, surfacing expiry/scope problems early instead of mid-operation.
   * @returns {Promise<Object>} The Graph API token debug payload describing validity and scopes.
   */
  async validateToken() {
    try {
      const response = await axios.get(`${FACEBOOK_GRAPH_API_BASE}/debug_token`, {
        params: {
          input_token: this.accessToken,
          access_token: `${this.appId}|${this.appSecret}`
        }
      });
      const data = response.data.data;
      if (!data.is_valid) {
        throw new Error('Access token is invalid');
      }
      return data;
    } catch (error) {
      throw this.formatError(error, 'Failed to validate access token');
    }
  }

  /**
   * @description Centralize every Graph API call so authentication, rate limiting, exponential-backoff retries, and error normalization are applied uniformly across all tools.
   * @param {string} method - HTTP verb for the request (e.g. GET, POST, DELETE).
   * @param {string} endpoint - Graph API path appended to the versioned base URL.
   * @param {Object|null} [data=null] - Request body for writes, or merged query params for GET requests.
   * @param {Object} [params={}] - Additional query string parameters.
   * @param {number} [retryCount=0] - Current retry attempt, used internally to bound backoff recursion.
   * @returns {Promise<Object>} The parsed Graph API response body.
   */
  async makeRequest(method, endpoint, data = null, params = {}, retryCount = 0) {
    await this.rateLimiter.waitForToken();

    const url = `${FACEBOOK_GRAPH_API_BASE}${endpoint}`;
    const config = {
      method,
      url,
      params: { access_token: this.accessToken, ...params },
      headers: { 'Content-Type': 'application/json' },
    };

    if (data) {
      if (method === 'GET') {
        config.params = { ...config.params, ...data };
      } else {
        config.data = data;
      }
    }

    try {
      const response = await axios(config);
      return response.data;
    } catch (error) {
      // Rate limiting retry
      if (error.response?.status === 429 || error.response?.data?.error?.code === 4) {
        if (retryCount < MAX_RETRIES) {
          const backoffTime = INITIAL_BACKOFF_MS * Math.pow(2, retryCount);
          await new Promise(resolve => setTimeout(resolve, backoffTime));
          return this.makeRequest(method, endpoint, data, params, retryCount + 1);
        }
        throw this.formatError(error, 'Rate limit exceeded after max retries');
      }

      // Auth errors
      if (error.response?.status === 401 || error.response?.data?.error?.code === 190) {
        throw this.formatError(error, 'Authentication failed. Token may be expired or invalid.', 'AUTH_ERROR');
      }

      // Network errors with retry
      if (!error.response && retryCount < MAX_RETRIES) {
        const backoffTime = INITIAL_BACKOFF_MS * Math.pow(2, retryCount);
        await new Promise(resolve => setTimeout(resolve, backoffTime));
        return this.makeRequest(method, endpoint, data, params, retryCount + 1);
      }

      throw this.formatError(error, 'API request failed');
    }
  }

  /**
   * @description Translate raw axios/Graph API failures into a single enriched Error shape, so upstream callers get consistent codes, trace IDs, and messages regardless of failure origin.
   * @param {Error} error - The original error thrown by axios or the Graph API.
   * @param {string} message - Human-readable summary of what operation failed.
   * @param {string|null} [code=null] - Explicit error code override; falls back to the Facebook error code or UNKNOWN_ERROR.
   * @returns {Error} A new Error annotated with Facebook error metadata.
   */
  formatError(error, message, code = null) {
    const formattedError = new Error(message);
    formattedError.originalError = error;
    formattedError.code = code || error.response?.data?.error?.code || 'UNKNOWN_ERROR';
    formattedError.type = error.response?.data?.error?.type || 'UnknownError';
    formattedError.fbTraceId = error.response?.data?.error?.fbtrace_id;
    formattedError.statusCode = error.response?.status;
    if (error.response?.data?.error) {
      formattedError.fbMessage = error.response.data.error.message;
      formattedError.fbError = error.response.data.error;
    }
    return formattedError;
  }
}

// ---------------------------------------------------------------------------
// Credential guard — wraps every tool that needs Facebook credentials
// ---------------------------------------------------------------------------

const NOT_CONNECTED_RESPONSE = {
  success: false,
  error: 'NOT_CONNECTED',
  message: 'Facebook is not connected. Connect via Settings > Integrations > Facebook, or say "connect to Facebook" and I will provide the authorization link.',
};

/**
 * Build a FacebookAPIClient from stored credentials.
 * Returns null if no credentials are available.
 */
function buildClientFromStore() {
  const creds = credentialStore.getCachedCredentials() || credentialStore.loadCredentials();
  if (!creds || !creds.facebookPageAccessToken) return null;

  return new FacebookAPIClient({
    accessToken: creds.facebookPageAccessToken,
    pageId: creds.facebookPageId,
    appId: process.env.FACEBOOK_APP_ID,
    appSecret: process.env.FACEBOOK_APP_SECRET,
  });
}

/**
 * Wrap a tool function with credential guard.
 * If credentials are missing, returns NOT_CONNECTED_RESPONSE.
 * Otherwise passes a ready-to-use client to the tool function.
 */
function withCredentials(toolFn) {
  return async function guarded(params) {
    const client = buildClientFromStore();
    if (!client) return { ...NOT_CONNECTED_RESPONSE };
    return toolFn(params, client);
  };
}

// ---------------------------------------------------------------------------
// Tools
// ---------------------------------------------------------------------------

/**
 * Check Facebook connection status.
 */
async function facebookStatus() {
  const creds = credentialStore.getCachedCredentials() || credentialStore.loadCredentials();

  if (!creds || !creds.facebookPageAccessToken) {
    return {
      connected: false,
      message: 'Facebook is not connected. Connect via Settings > Integrations > Facebook.',
    };
  }

  // Validate token with Facebook
  const client = new FacebookAPIClient({
    accessToken: creds.facebookPageAccessToken,
    pageId: creds.facebookPageId,
    appId: process.env.FACEBOOK_APP_ID,
    appSecret: process.env.FACEBOOK_APP_SECRET,
  });

  try {
    const tokenInfo = await client.validateToken();
    return {
      connected: true,
      pageId: creds.facebookPageId,
      pageName: creds.facebookPageName,
      connectedAt: creds.facebookConnectedAt,
      tokenValid: true,
      tokenExpiresAt: creds.facebookTokenExpiresAt,
      scopes: tokenInfo.scopes || [],
      needsRefresh: credentialStore.needsRefresh(),
      message: `Connected to Facebook page "${creds.facebookPageName}" (ID: ${creds.facebookPageId})`,
    };
  } catch (error) {
    return {
      connected: true,
      pageId: creds.facebookPageId,
      pageName: creds.facebookPageName,
      tokenValid: false,
      error: error.message,
      message: `Facebook credentials stored for page "${creds.facebookPageName}" but token validation failed: ${error.message}`,
    };
  }
}

/**
 * Post content to Facebook page.
 */
const facebookPost = withCredentials(async (params, client) => {
  const { message, link, image_url, published = true, scheduled_publish_time } = params;

  if (!message && !link && !image_url) {
    throw new Error('At least one of message, link, or image_url is required');
  }

  const postData = { message: message || '' };

  if (link) {
    postData.link = link;
  }

  if (image_url) {
    postData.url = image_url;
    const endpoint = `/${client.pageId}/photos`;
    const result = await client.makeRequest('POST', endpoint, postData);
    return {
      success: true,
      post_id: result.id,
      post_url: `https://facebook.com/${result.id}`,
      message: 'Photo posted successfully',
    };
  }

  if (scheduled_publish_time) {
    postData.published = false;
    postData.scheduled_publish_time = scheduled_publish_time;
  } else {
    postData.published = published;
  }

  const endpoint = `/${client.pageId}/feed`;
  const result = await client.makeRequest('POST', endpoint, postData);

  return {
    success: true,
    post_id: result.id,
    post_url: `https://facebook.com/${result.id}`,
    message: scheduled_publish_time ? 'Post scheduled successfully' : 'Post published successfully',
  };
});

/**
 * Read Facebook page feed.
 */
const facebookReadFeed = withCredentials(async (params = {}, client) => {
  const { limit = 25, since, until, fields } = params;

  if (limit > 100) {
    throw new Error('Limit cannot exceed 100');
  }

  const requestParams = {
    limit,
    fields: fields?.join(',') || 'id,message,created_time,permalink_url,reactions.limit(0).summary(true),comments.limit(0).summary(true),shares',
  };

  if (since) requestParams.since = since;
  if (until) requestParams.until = until;

  const endpoint = `/${client.pageId}/feed`;
  const result = await client.makeRequest('GET', endpoint, null, requestParams);

  const posts = result.data.map(post => ({
    id: post.id,
    message: post.message || '',
    created_time: post.created_time,
    permalink_url: post.permalink_url,
    reactions_count: post.reactions?.summary?.total_count || 0,
    comments_count: post.comments?.summary?.total_count || 0,
    shares_count: post.shares?.count || 0,
  }));

  return {
    success: true,
    posts,
    count: posts.length,
    paging: result.paging,
    message: `Retrieved ${posts.length} posts successfully`,
  };
});

/**
 * Reply to a Facebook comment.
 */
const facebookReplyComment = withCredentials(async (params, client) => {
  const { comment_id, message, attachment_url } = params;

  if (!comment_id) throw new Error('comment_id is required');
  if (!message && !attachment_url) throw new Error('Either message or attachment_url is required');

  const replyData = {};
  if (message) replyData.message = message;
  if (attachment_url) replyData.attachment_url = attachment_url;

  const endpoint = `/${comment_id}/comments`;
  const result = await client.makeRequest('POST', endpoint, replyData);

  return { success: true, comment_id: result.id, message: 'Reply posted successfully' };
});

/**
 * Get comments for a specific post.
 */
const facebookGetComments = withCredentials(async (params, client) => {
  const { post_id, limit = 25, order = 'chronological' } = params;

  if (!post_id) throw new Error('post_id is required');

  const requestParams = {
    limit,
    order,
    fields: 'id,from,message,created_time,like_count,comment_count,parent',
  };

  const endpoint = `/${post_id}/comments`;
  const result = await client.makeRequest('GET', endpoint, null, requestParams);

  const comments = result.data.map(comment => ({
    id: comment.id,
    from: comment.from,
    message: comment.message || '',
    created_time: comment.created_time,
    like_count: comment.like_count || 0,
    reply_count: comment.comment_count || 0,
    parent_id: comment.parent?.id,
  }));

  return {
    success: true,
    comments,
    count: comments.length,
    paging: result.paging,
    message: `Retrieved ${comments.length} comments successfully`,
  };
});

/**
 * Delete a post.
 */
const facebookDeletePost = withCredentials(async (params, client) => {
  const { post_id } = params;
  if (!post_id) throw new Error('post_id is required');

  const endpoint = `/${post_id}`;
  const result = await client.makeRequest('DELETE', endpoint);

  return { success: result.success || true, message: 'Post deleted successfully' };
});

/**
 * Refresh the Facebook access token.
 */
const facebookRefreshToken = withCredentials(async (params, client) => {
  const creds = credentialStore.getCachedCredentials();
  const tokenToRefresh = creds?.facebookUserAccessToken || creds?.facebookPageAccessToken;

  if (!tokenToRefresh) throw new Error('No token available to refresh');

  const response = await axios.get(`${FACEBOOK_GRAPH_API_BASE}/oauth/access_token`, {
    params: {
      grant_type: 'fb_exchange_token',
      client_id: client.appId,
      client_secret: client.appSecret,
      fb_exchange_token: tokenToRefresh,
    },
  });

  const newToken = response.data.access_token;
  const expiresIn = response.data.expires_in;
  const expiresAt = expiresIn ? Date.now() + (expiresIn * 1000) : null;

  // If we have a user token, get a fresh page token
  let pageToken = newToken;
  if (creds.facebookPageId) {
    try {
      const pagesResponse = await axios.get(`${FACEBOOK_GRAPH_API_BASE}/me/accounts`, {
        params: { access_token: newToken, fields: 'id,access_token' },
      });
      const page = pagesResponse.data.data.find(p => p.id === creds.facebookPageId);
      if (page) pageToken = page.access_token;
    } catch (err) {
      // Fall back to using the refreshed token directly
    }
  }

  // Persist refreshed credentials
  credentialStore.saveCredentials({
    ...creds,
    facebookUserAccessToken: newToken,
    facebookPageAccessToken: pageToken,
    facebookTokenExpiresAt: expiresAt,
  });

  return {
    success: true,
    expiresAt,
    message: 'Token refreshed successfully',
  };
});

// ─── Export with snake_case keys matching mcp_tools[].name in persona YAML ──
module.exports = {
  facebook_status: facebookStatus,
  facebook_post: facebookPost,
  facebook_read_feed: facebookReadFeed,
  facebook_reply_comment: facebookReplyComment,
  facebook_get_comments: facebookGetComments,
  facebook_delete_post: facebookDeletePost,
  facebook_refresh_token: facebookRefreshToken,
  // Named exports for direct require() usage
  facebookStatus,
  facebookPost,
  facebookReadFeed,
  facebookReplyComment,
  facebookGetComments,
  facebookDeletePost,
  facebookRefreshToken,
  FacebookAPIClient,
  RateLimiter,
};
