/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * SEQ                 | AUTHOR                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 1 | maintainer@emeraldcoastsystemsgroup.com   | Markdown + Mermaid rendering for the schema docs. Pure functions over folded table records: an erDiagram per page (key columns only - PK / FK / UNIQUE / RLS owner - so a 40-table page stays legible), a full column table per table, RLS row-scope lines, and marker-delimited block replacement so hand-written README prose survives regeneration. Output is deterministic (sorted, no timestamps) so an unchanged schema regenerates to a zero diff.
 * 2 | maintainer@emeraldcoastsystemsgroup.com   | The erDiagram renderer is no longer a copy. mermaidType/mermaidName/keyRoles/mermaidDiagram now delegate to src/pages/data-model/js/er-diagram.mjs, the single implementation the data-model explorer's Export also imports, so the committed pages and the surface cannot drift apart between parity runs. Only the owner-column reader stays here: the generator classifies the policies itself through summarizeRowAccess, where the page is handed the server's summary.
 */

'use strict';

const { summarizeRowAccess } = require('./row-access');
// THE erDiagram renderer, shared verbatim with the data-model explorer's Export. Plain ESM with
// no imports, so the browser loads it straight off the page mount. require() of an ES module
// needs Node 20.19+/22.12+ - the same floor this repo's vitest already needs to start at all.
const erDiagram = require('../../src/pages/data-model/js/er-diagram.mjs');

const GENERATED_BANNER = '<!-- GENERATED by scripts/generate-schema-docs.js - do not edit by hand; regenerate instead. -->';

/**
 * @description The RLS owner columns of a table, classified here from its policies - the schema-docs
 * generator reads a raw catalog record, where the explorer is handed the server's own summary.
 * @param {object} table - folded table record
 * @returns {string[]} owner column names
 */
const ownerColumnsOf = (table) => summarizeRowAccess(table).ownerColumns;

const { mermaidType, mermaidName } = erDiagram;

/**
 * @description Escape text for a markdown table cell.
 * @param {*} value - any value
 * @returns {string} single-line cell text with pipes escaped
 */
function cell(value) {
  if (value === null || value === undefined || value === '') return '';
  return String(value).replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();
}

/**
 * @description Count with a correctly pluralised noun.
 * @param {number} n - count
 * @param {string} noun - singular noun
 * @returns {string} e.g. `1 view`, `3 views`
 */
function plural(n, noun) {
  return `${n} ${noun}${n === 1 ? '' : 's'}`;
}

/**
 * @description Tidy a column default for display: drop the literal casts Postgres adds
 * (`'x'::text` → `'x'`, `nextval('s'::regclass)` → `nextval('s')`) and cap very long expressions.
 * @param {string|null} def - raw default expression
 * @returns {string} display text
 */
function displayDefault(def) {
  if (!def) return '';
  const tidy = String(def).replace(/^('(?:[^']|'')*')::[\w ]+(\[\])?$/, '$1').replace(/::regclass\)/g, ')');
  return tidy.length > 60 ? `${tidy.slice(0, 57)}...` : tidy;
}

/**
 * @description Which of a table's columns carry a key role, for the diagram and notes.
 * @param {object} table - folded table record
 * @returns {Map<string, string[]>} column -> roles among PK / FK / UK / owner
 */
function keyRoles(table) {
  return erDiagram.keyRoles(table, ownerColumnsOf);
}

/**
 * @description Render one erDiagram for a page's tables. FKs to tables outside the page still
 * draw - the external parent appears as a bare entity box.
 * @param {object[]} tables - folded table records on this page
 * @returns {string} fenced mermaid block
 */
function mermaidDiagram(tables) {
  return erDiagram.mermaidDiagram(tables, ownerColumnsOf);
}

/**
 * @description Notes cell for one column: key roles, FK target (linked when the target is
 * documented), and the column comment.
 * @param {object} table - folded table record
 * @param {object} col - column record
 * @param {{linkFor: function(string, string): string}} ctx - renders a `table.column` reference
 * @returns {string} notes text
 */
function columnNotes(table, col, ctx) {
  const roles = keyRoles(table).get(col.name) || [];
  const parts = roles.filter((r) => r !== 'FK');
  for (const fk of table.foreignKeys.filter((f) => f.columns.includes(col.name))) {
    const i = fk.columns.indexOf(col.name);
    parts.push(`FK → ${ctx.linkFor(fk.refTable, fk.refColumns[i] || fk.refColumns[0] || '')}`);
  }
  if (col.comment) parts.push(col.comment);
  return parts.join(' · ');
}

/**
 * @description Full markdown section for one table.
 * @param {object} table - folded table record
 * @param {{linkFor: function, definersOf: function(string): string[], noteFor: function(string): string|null}} ctx
 * @returns {string} markdown
 */
function tableSection(table, ctx) {
  const access = summarizeRowAccess(table);
  const meta = [];
  const definers = ctx.definersOf(table.name);
  if (definers.length) meta.push(`Defined in ${definers.map((f) => `\`${f}\``).join(', ')}`);
  if (access.state !== 'n/a') meta.push(`RLS **${access.state}**${access.scopes.length ? ` - ${access.scopes.join('; ')}` : ''}`);
  if (table.hypertable) meta.push(`TimescaleDB hypertable on \`${table.hypertable.timeColumn}\``);
  const note = ctx.noteFor ? ctx.noteFor(table.name) : null;
  const out = [`### \`${table.name}\``, ''];
  if (table.comment) out.push(`> ${cell(table.comment)}`, '');
  if (meta.length) out.push(meta.join(' · '), '');
  if (note) out.push(note, '');
  out.push('| Column | Type | Null | Default | Notes |', '|---|---|---|---|---|');
  for (const c of table.columns) {
    out.push(`| \`${c.name}\` | ${cell(c.type)} | ${c.nullable ? 'yes' : 'no'} | ${cell(displayDefault(c.default))} | ${cell(columnNotes(table, c, ctx))} |`);
  }
  return out.join('\n');
}

/**
 * @description Markdown section for one view: its columns and the files that create it. Views
 * carry no keys or policies of their own (a security_invoker view is scoped by the RLS of the
 * tables it reads), so the section is columns only.
 * @param {object} view - folded view record
 * @param {string[]} definers - files holding its CREATE VIEW
 * @returns {string} markdown
 */
function viewSection(view, definers) {
  const out = [`### \`${view.name}\``, ''];
  const meta = [view.materialized ? 'Materialized view' : 'View'];
  if (definers.length) meta.push(`defined in ${definers.map((f) => `\`${f}\``).join(', ')}`);
  out.push(meta.join(' '), '');
  if (view.comment) out.push(`> ${cell(view.comment)}`, '');
  out.push('| Column | Type |', '|---|---|');
  for (const c of view.columns) out.push(`| \`${c.name}\` | ${cell(c.type)} |`);
  return out.join('\n');
}

/**
 * @description Replace the content between `<!-- schema-docs:begin:NAME -->` and
 * `<!-- schema-docs:end:NAME -->`, leaving everything else (hand-written prose) intact.
 * @param {string} text - document text
 * @param {string} name - block name
 * @param {string} content - new block content
 * @returns {string} updated text
 * @throws {Error} when the markers are missing, so a renamed block fails loudly instead of silently not updating
 */
function replaceBlock(text, name, content) {
  const begin = `<!-- schema-docs:begin:${name} -->`;
  const end = `<!-- schema-docs:end:${name} -->`;
  const a = text.indexOf(begin);
  const b = text.indexOf(end);
  if (a === -1 || b === -1 || b < a) throw new Error(`schema-docs block "${name}" markers not found`);
  return `${text.slice(0, a + begin.length)}\n${content}\n${text.slice(b)}`;
}

module.exports = {
  GENERATED_BANNER, mermaidType, mermaidName, mermaidDiagram, tableSection, viewSection, replaceBlock, cell, displayDefault, keyRoles, plural,
};
