/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * SEQ                 | AUTHOR                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 1 | maintainer@emeraldcoastsystemsgroup.com   | Markdown + Mermaid rendering for the schema docs. Pure functions over folded table records: an erDiagram per page (key columns only - PK / FK / UNIQUE / RLS owner - so a 40-table page stays legible), a full column table per table, RLS row-scope lines, and marker-delimited block replacement so hand-written README prose survives regeneration. Output is deterministic (sorted, no timestamps) so an unchanged schema regenerates to a zero diff.
 */

'use strict';

const { summarizeRowAccess } = require('./row-access');

const GENERATED_BANNER = '<!-- GENERATED by scripts/generate-schema-docs.js - do not edit by hand; regenerate instead. -->';

const TYPE_ALIASES = [
  [/^timestamp(\(\d+\))? with time zone/, 'timestamptz'],
  [/^timestamp(\(\d+\))? without time zone/, 'timestamp'],
  [/^time(\(\d+\))? with time zone/, 'timetz'],
  [/^character varying/i, 'varchar'],
  [/^character\b/i, 'char'],
  [/^double precision/i, 'float8'],
  [/^bit varying/i, 'varbit'],
];

/**
 * @description Reduce a Postgres/SQLite type to a Mermaid-legal attribute type token.
 * @param {string} type - e.g. `timestamp with time zone`, `character varying(64)`, `text[]`
 * @returns {string} e.g. `timestamptz`, `varchar`, `text_array`
 */
function mermaidType(type) {
  const raw = String(type || 'unknown').trim();
  const isArray = /\[\]$/.test(raw);
  let base = raw.replace(/\[\]$/, '');
  const alias = TYPE_ALIASES.find(([re]) => re.test(base));
  base = alias ? alias[1] : base.replace(/\(.*\)/, '');
  base = base.replace(/[^A-Za-z0-9_]+/g, '_').replace(/^_+|_+$/g, '') || 'unknown';
  return isArray ? `${base}_array` : base;
}

/**
 * @description Make any identifier safe as a Mermaid entity or attribute name.
 * @param {string} name - raw identifier
 * @returns {string} identifier with only [A-Za-z0-9_-]
 */
function mermaidName(name) {
  const safe = String(name).replace(/[^A-Za-z0-9_-]/g, '_');
  return /^[A-Za-z_]/.test(safe) ? safe : `_${safe}`;
}

/**
 * @description Escape text for a markdown table cell.
 * @param {*} value - any value
 * @returns {string} single-line cell text with pipes escaped
 */
function cell(value) {
  if (value === null || value === undefined || value === '') return '';
  return String(value).replace(/\s+/g, ' ').replace(/\|/g, '\\|').trim();
}

/**
 * @description Count with a correctly pluralised noun.
 * @param {number} n - count
 * @param {string} noun - singular noun
 * @returns {string} e.g. `1 view`, `3 views`
 */
function plural(n, noun) {
  return `${n} ${noun}${n === 1 ? '' : 's'}`;
}

/**
 * @description Tidy a column default for display: drop the literal casts Postgres adds
 * (`'x'::text` → `'x'`, `nextval('s'::regclass)` → `nextval('s')`) and cap very long expressions.
 * @param {string|null} def - raw default expression
 * @returns {string} display text
 */
function displayDefault(def) {
  if (!def) return '';
  const tidy = String(def).replace(/^('(?:[^']|'')*')::[\w ]+(\[\])?$/, '$1').replace(/::regclass\)/g, ')');
  return tidy.length > 60 ? `${tidy.slice(0, 57)}...` : tidy;
}

/**
 * @description Which of a table's columns carry a key role, for the diagram and notes.
 * @param {object} table - folded table record
 * @returns {Map<string, string[]>} column -> roles among PK / FK / UK / owner
 */
function keyRoles(table) {
  const roles = new Map();
  const add = (col, role) => { if (!roles.has(col)) roles.set(col, []); if (!roles.get(col).includes(role)) roles.get(col).push(role); };
  table.primaryKey.forEach((c) => add(c, 'PK'));
  table.foreignKeys.forEach((fk) => fk.columns.forEach((c) => add(c, 'FK')));
  table.uniques.filter((u) => u.length === 1).forEach((u) => add(u[0], 'UK'));
  summarizeRowAccess(table).ownerColumns.forEach((c) => add(c, 'owner'));
  return roles;
}

/**
 * @description Mermaid attribute lines for one table (key columns only; first column when keyless).
 * @param {object} table - folded table record
 * @returns {string[]} indented attribute lines
 */
function diagramAttributes(table) {
  const roles = keyRoles(table);
  const cols = table.columns.filter((c) => roles.has(c.name));
  const shown = cols.length ? cols : table.columns.slice(0, 1);
  return shown.map((c) => {
    const r = roles.get(c.name) || [];
    const keys = r.filter((x) => x !== 'owner').join(', ');
    const note = r.includes('owner') ? ' "owner"' : '';
    return `    ${mermaidType(c.type)} ${mermaidName(c.name)}${keys ? ` ${keys}` : ''}${note}`;
  });
}

/**
 * @description Mermaid relationship line for one FK (parent on the left, child on the right).
 * @param {object} table - child table record
 * @param {object} fk - {columns, refTable}
 * @returns {string} e.g. `  tickets ||--o{ work_items : "ticket_id"`
 */
function relationshipLine(table, fk) {
  const cols = fk.columns;
  const nullable = cols.some((c) => table.columns.find((x) => x.name === c)?.nullable !== false);
  const unique = [table.primaryKey, ...table.uniques].some((k) => k.length === cols.length && cols.every((c) => k.includes(c)));
  const left = nullable ? '|o' : '||';
  const right = unique ? 'o|' : 'o{';
  return `  ${mermaidName(fk.refTable)} ${left}--${right} ${mermaidName(table.name)} : "${cols.join(', ')}"`;
}

/**
 * @description Render one erDiagram for a page's tables. FKs to tables outside the page still
 * draw - the external parent appears as a bare entity box.
 * @param {object[]} tables - folded table records on this page
 * @returns {string} fenced mermaid block
 */
function mermaidDiagram(tables) {
  const lines = ['```mermaid', 'erDiagram'];
  for (const t of tables) lines.push(`  ${mermaidName(t.name)} {`, ...diagramAttributes(t), '  }');
  const seen = new Set();
  for (const t of tables) {
    for (const fk of t.foreignKeys) {
      if (!fk.refTable) continue;
      const line = relationshipLine(t, fk);
      if (!seen.has(line)) { seen.add(line); lines.push(line); }
    }
  }
  lines.push('```');
  return lines.join('\n');
}

/**
 * @description Notes cell for one column: key roles, FK target (linked when the target is
 * documented), and the column comment.
 * @param {object} table - folded table record
 * @param {object} col - column record
 * @param {{linkFor: function(string, string): string}} ctx - renders a `table.column` reference
 * @returns {string} notes text
 */
function columnNotes(table, col, ctx) {
  const roles = keyRoles(table).get(col.name) || [];
  const parts = roles.filter((r) => r !== 'FK');
  for (const fk of table.foreignKeys.filter((f) => f.columns.includes(col.name))) {
    const i = fk.columns.indexOf(col.name);
    parts.push(`FK → ${ctx.linkFor(fk.refTable, fk.refColumns[i] || fk.refColumns[0] || '')}`);
  }
  if (col.comment) parts.push(col.comment);
  return parts.join(' · ');
}

/**
 * @description Full markdown section for one table.
 * @param {object} table - folded table record
 * @param {{linkFor: function, definersOf: function(string): string[], noteFor: function(string): string|null}} ctx
 * @returns {string} markdown
 */
function tableSection(table, ctx) {
  const access = summarizeRowAccess(table);
  const meta = [];
  const definers = ctx.definersOf(table.name);
  if (definers.length) meta.push(`Defined in ${definers.map((f) => `\`${f}\``).join(', ')}`);
  if (access.state !== 'n/a') meta.push(`RLS **${access.state}**${access.scopes.length ? ` - ${access.scopes.join('; ')}` : ''}`);
  if (table.hypertable) meta.push(`TimescaleDB hypertable on \`${table.hypertable.timeColumn}\``);
  const note = ctx.noteFor ? ctx.noteFor(table.name) : null;
  const out = [`### \`${table.name}\``, ''];
  if (table.comment) out.push(`> ${cell(table.comment)}`, '');
  if (meta.length) out.push(meta.join(' · '), '');
  if (note) out.push(note, '');
  out.push('| Column | Type | Null | Default | Notes |', '|---|---|---|---|---|');
  for (const c of table.columns) {
    out.push(`| \`${c.name}\` | ${cell(c.type)} | ${c.nullable ? 'yes' : 'no'} | ${cell(displayDefault(c.default))} | ${cell(columnNotes(table, c, ctx))} |`);
  }
  return out.join('\n');
}

/**
 * @description Markdown section for one view: its columns and the files that create it. Views
 * carry no keys or policies of their own (a security_invoker view is scoped by the RLS of the
 * tables it reads), so the section is columns only.
 * @param {object} view - folded view record
 * @param {string[]} definers - files holding its CREATE VIEW
 * @returns {string} markdown
 */
function viewSection(view, definers) {
  const out = [`### \`${view.name}\``, ''];
  const meta = [view.materialized ? 'Materialized view' : 'View'];
  if (definers.length) meta.push(`defined in ${definers.map((f) => `\`${f}\``).join(', ')}`);
  out.push(meta.join(' '), '');
  if (view.comment) out.push(`> ${cell(view.comment)}`, '');
  out.push('| Column | Type |', '|---|---|');
  for (const c of view.columns) out.push(`| \`${c.name}\` | ${cell(c.type)} |`);
  return out.join('\n');
}

/**
 * @description Replace the content between `<!-- schema-docs:begin:NAME -->` and
 * `<!-- schema-docs:end:NAME -->`, leaving everything else (hand-written prose) intact.
 * @param {string} text - document text
 * @param {string} name - block name
 * @param {string} content - new block content
 * @returns {string} updated text
 * @throws {Error} when the markers are missing, so a renamed block fails loudly instead of silently not updating
 */
function replaceBlock(text, name, content) {
  const begin = `<!-- schema-docs:begin:${name} -->`;
  const end = `<!-- schema-docs:end:${name} -->`;
  const a = text.indexOf(begin);
  const b = text.indexOf(end);
  if (a === -1 || b === -1 || b < a) throw new Error(`schema-docs block "${name}" markers not found`);
  return `${text.slice(0, a + begin.length)}\n${content}\n${text.slice(b)}`;
}

module.exports = {
  GENERATED_BANNER, mermaidType, mermaidName, mermaidDiagram, tableSection, viewSection, replaceBlock, cell, displayDefault, keyRoles, plural,
};
