/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * SEQ                 | AUTHOR                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 1 | maintainer@emeraldcoastsystemsgroup.com   | Extracted persona tool seed catalog from ToolRegistryService for file-size compliance
 * 2 | maintainer@emeraldcoastsystemsgroup.com   | Restored compile compatibility by de-contextualizing extracted persona seed literals before CreateToolInput cast
 * 3 | maintainer@emeraldcoastsystemsgroup.com   | Seed `conversation-query`, the read-only tool that lets a bot answer from what the caller has already said to this swarm instead of asking them to repeat it. Seeded HERE rather than beside rag-query/graph-query in tool-registry-baseline-tools.ts because that file stands at 829 code lines - past the 800-line mark where the house rule says stop and propose a decomposition before adding. Both arrays are seeded by the same seedBaselineAgentTools pass, so placement changes nothing a caller can observe.
 */

import type { CreateToolInput } from '@/entities/tool';

/**
 * @description Persona-scoped seed tools referenced by bot persona YAMLs.
 * Kept in a dedicated module to keep ToolRegistryService within file-size limits.
 */
export const TOOL_REGISTRY_PERSONA_TOOLS = [
  {
    name: 'bash',
    displayName: 'Bash Shell',
    type: 'cli',
    category: 'development',
    version: '5.x',
    installSpec: { method: 'binary', verifyCommand: 'bash --version' },
    skills: ['shell', 'scripting', 'automation'],
    selectorFragment: 'Bash shell execution is available when authorized.',
    routingTags: ['bash', 'shell', 'scripting'],
    authGroup: 'development',
    defaultAuthMode: 'off',
    description: 'Execute bash shell commands directly for scripting and automation tasks.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use execute_command with bash for shell scripting workflows.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['bash', 'shell', 'cli'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'browser',
    displayName: 'Browser Automation',
    type: 'mcp',
    category: 'web',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['browser', 'web-interaction', 'playwright'],
    selectorFragment: 'Browser automation via Playwright is available when authorized.',
    routingTags: ['browser', 'playwright', 'web'],
    authGroup: 'browser',
    defaultAuthMode: 'off',
    description: 'Browser automation and web interaction via Playwright MCP server.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use the browser tool for web page interaction and testing.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 120000,
    tags: ['browser', 'playwright', 'mcp'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'read-file',
    displayName: 'Read File',
    type: 'mcp',
    category: 'filesystem',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['file-read', 'filesystem'],
    selectorFragment: 'File reading is available through the filesystem MCP when authorized.',
    routingTags: ['read-file', 'filesystem'],
    authGroup: 'filesystem',
    defaultAuthMode: 'off',
    description: 'Read file contents from the filesystem via MCP server.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use read_file to examine file contents within the workspace.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 30000,
    tags: ['file', 'read', 'mcp'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'write-file',
    displayName: 'Write File',
    type: 'mcp',
    category: 'filesystem',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['file-write', 'filesystem'],
    selectorFragment: 'File writing is available through the filesystem MCP when authorized.',
    routingTags: ['write-file', 'filesystem'],
    authGroup: 'filesystem',
    defaultAuthMode: 'off',
    description: 'Write content to files on the filesystem via MCP server.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use write_file to create or update files within the workspace.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 30000,
    tags: ['file', 'write', 'mcp'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'fetch',
    displayName: 'HTTP Fetch',
    type: 'mcp',
    category: 'web',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['http', 'fetch', 'web-request'],
    selectorFragment: 'HTTP fetch for URLs is available through the fetch MCP when authorized.',
    routingTags: ['fetch', 'http', 'web'],
    authGroup: 'web',
    defaultAuthMode: 'off',
    description: 'Fetch resources from URLs via HTTP using the fetch MCP server.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use fetch to retrieve web resources and API responses.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 30000,
    tags: ['fetch', 'http', 'mcp'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'chroma-mcp',
    displayName: 'ChromaDB MCP',
    type: 'mcp',
    category: 'ai',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['vector-store', 'chromadb', 'embeddings'],
    selectorFragment: 'ChromaDB vector store operations are available through chroma-mcp when authorized.',
    routingTags: ['chroma', 'vector', 'embeddings'],
    authGroup: 'ai',
    defaultAuthMode: 'off',
    description: 'ChromaDB vector store operations via MCP for RAG and embedding workflows.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use chroma-mcp for vector store CRUD and similarity search operations.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['chroma', 'mcp', 'vector'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'plane-mcp',
    displayName: 'Plane MCP',
    type: 'mcp',
    category: 'project-management',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['project-management', 'plane', 'tickets'],
    selectorFragment: 'Plane project management operations are available through plane-mcp when authorized.',
    routingTags: ['plane', 'tickets', 'project'],
    authGroup: 'project-management',
    defaultAuthMode: 'off',
    description: 'Plane project management operations via MCP for ticket and project workflows.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use plane-mcp to manage tickets, projects, and sprints in Plane.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['plane', 'mcp', 'project'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'conversation-query',
    displayName: 'Conversation History Query',
    type: 'api',
    category: 'knowledge',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['conversation-query', 'recall', 'history', 'answer-synthesis'],
    selectorFragment:
      "The caller's own past conversations with this swarm are searchable, so a question about what was already said, asked or decided is answered from the record.",
    routingTags: ['conversation', 'history', 'recall', 'chat'],
    authGroup: 'agent-tools',
    // Read-only and owner-scoped, and the thing a front-door assistant is asked for most often is
    // something it was already told. Default ON for the same reason rag-query is: the alternative
    // to grounding an answer in the record is inventing one.
    defaultAuthMode: 'auto',
    description:
      "Search the caller's OWN past conversations with this swarm and return the matching conversations with a snippet and a link. Scoped to the caller by row-level security on chat_tasks - another person's conversations are refused by the database, not filtered in application code. Read-only: it never writes, renames or deletes a conversation.",
    inputSchema: {
      type: 'object',
      required: ['query'],
      properties: {
        query: { type: 'string', description: 'Words to look for in past conversations.' },
        limit: { type: 'integer', description: 'Maximum conversations to return (1-25).' },
      },
    },
    outputSchema: {
      type: 'object',
      properties: {
        conversations: { type: 'array', items: { type: 'object' } },
      },
    },
    usageInstructions:
      "Call conversation_query with the words the caller used when asking 'what did we decide about X', 'did I already ask you about Y', or 'what was that thing I mentioned'. Each hit carries taskId, title, snippet, updatedAt and a cockpit link - cite the title and the link rather than paraphrasing a snippet as if it were new. An empty result means the record holds nothing matching, not that the caller never said it: say so plainly instead of inventing a recollection.",
    examples: [],
    requiresApproval: false,
    timeoutMs: 30000,
    tags: ['conversation', 'history', 'recall', 'read-only'],
    enabled: true,
    registeredBy: 'system',
  },
] as unknown as CreateToolInput[];
