/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * SEQ                 | AUTHOR                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 1 | maintainer@emeraldcoastsystemsgroup.com   | Extracted persona tool seed catalog from ToolRegistryService for file-size compliance
 * 2 | maintainer@emeraldcoastsystemsgroup.com   | Restored compile compatibility by de-contextualizing extracted persona seed literals before CreateToolInput cast
 */

import type { CreateToolInput } from '@/entities/tool';

/**
 * @description Persona-scoped seed tools referenced by bot persona YAMLs.
 * Kept in a dedicated module to keep ToolRegistryService within file-size limits.
 */
export const TOOL_REGISTRY_PERSONA_TOOLS = [
  {
    name: 'bash',
    displayName: 'Bash Shell',
    type: 'cli',
    category: 'development',
    version: '5.x',
    installSpec: { method: 'binary', verifyCommand: 'bash --version' },
    skills: ['shell', 'scripting', 'automation'],
    selectorFragment: 'Bash shell execution is available when authorized.',
    routingTags: ['bash', 'shell', 'scripting'],
    authGroup: 'development',
    defaultAuthMode: 'off',
    description: 'Execute bash shell commands directly for scripting and automation tasks.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use execute_command with bash for shell scripting workflows.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['bash', 'shell', 'cli'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'browser',
    displayName: 'Browser Automation',
    type: 'mcp',
    category: 'web',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['browser', 'web-interaction', 'playwright'],
    selectorFragment: 'Browser automation via Playwright is available when authorized.',
    routingTags: ['browser', 'playwright', 'web'],
    authGroup: 'browser',
    defaultAuthMode: 'off',
    description: 'Browser automation and web interaction via Playwright MCP server.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use the browser tool for web page interaction and testing.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 120000,
    tags: ['browser', 'playwright', 'mcp'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'read-file',
    displayName: 'Read File',
    type: 'mcp',
    category: 'filesystem',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['file-read', 'filesystem'],
    selectorFragment: 'File reading is available through the filesystem MCP when authorized.',
    routingTags: ['read-file', 'filesystem'],
    authGroup: 'filesystem',
    defaultAuthMode: 'off',
    description: 'Read file contents from the filesystem via MCP server.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use read_file to examine file contents within the workspace.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 30000,
    tags: ['file', 'read', 'mcp'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'write-file',
    displayName: 'Write File',
    type: 'mcp',
    category: 'filesystem',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['file-write', 'filesystem'],
    selectorFragment: 'File writing is available through the filesystem MCP when authorized.',
    routingTags: ['write-file', 'filesystem'],
    authGroup: 'filesystem',
    defaultAuthMode: 'off',
    description: 'Write content to files on the filesystem via MCP server.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use write_file to create or update files within the workspace.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 30000,
    tags: ['file', 'write', 'mcp'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'fetch',
    displayName: 'HTTP Fetch',
    type: 'mcp',
    category: 'web',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['http', 'fetch', 'web-request'],
    selectorFragment: 'HTTP fetch for URLs is available through the fetch MCP when authorized.',
    routingTags: ['fetch', 'http', 'web'],
    authGroup: 'web',
    defaultAuthMode: 'off',
    description: 'Fetch resources from URLs via HTTP using the fetch MCP server.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use fetch to retrieve web resources and API responses.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 30000,
    tags: ['fetch', 'http', 'mcp'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'chroma-mcp',
    displayName: 'ChromaDB MCP',
    type: 'mcp',
    category: 'ai',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['vector-store', 'chromadb', 'embeddings'],
    selectorFragment: 'ChromaDB vector store operations are available through chroma-mcp when authorized.',
    routingTags: ['chroma', 'vector', 'embeddings'],
    authGroup: 'ai',
    defaultAuthMode: 'off',
    description: 'ChromaDB vector store operations via MCP for RAG and embedding workflows.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use chroma-mcp for vector store CRUD and similarity search operations.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['chroma', 'mcp', 'vector'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'plane-mcp',
    displayName: 'Plane MCP',
    type: 'mcp',
    category: 'project-management',
    version: '1.0.0',
    installSpec: { method: 'none' },
    skills: ['project-management', 'plane', 'tickets'],
    selectorFragment: 'Plane project management operations are available through plane-mcp when authorized.',
    routingTags: ['plane', 'tickets', 'project'],
    authGroup: 'project-management',
    defaultAuthMode: 'off',
    description: 'Plane project management operations via MCP for ticket and project workflows.',
    inputSchema: { type: 'object', properties: {} },
    outputSchema: { type: 'object', properties: {} },
    usageInstructions: 'Use plane-mcp to manage tickets, projects, and sprints in Plane.',
    examples: [],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['plane', 'mcp', 'project'],
    enabled: true,
    registeredBy: 'system',
  },
] as unknown as CreateToolInput[];