/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * SEQ                 | AUTHOR                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 1 | maintainer@emeraldcoastsystemsgroup.com   | Extracted baseline tool seed catalog from ToolRegistryService for file-size governance compliance
 * 2 | maintainer@emeraldcoastsystemsgroup.com   | Restored compile compatibility by de-contextualizing extracted seed literals before CreateToolInput cast in dedicated baseline catalog module
 * 3 | maintainer@emeraldcoastsystemsgroup.com   | presentron catalog entry updated to describe the as-built tool: it now renders via the in-repo deck engine (@/features/presentation-generation renderPptx) into the task workspace, not the retired Presentron sidecar — description, input schema, usage, and tags reconciled with the executor swap in tool-executor-service.ts.
 * 4 | maintainer@emeraldcoastsystemsgroup.com   | ADR-045 closure: graph-query retargeted from the DEAD external graph service to the real tier. It advertised Cypher/Gremlin against Memgraph/Neo4j via $GRAPH_API_URL — a variable nothing sets and an engine the compose file strips — while the shipped tier is ArangoDB/AQL behind the caller-scoped /api/graph route. Every bot granted this tool (defaultAuthMode 'auto') was being instructed to curl a service that does not exist, so routingTags/description/inputSchema/usageInstructions now describe /api/graph, AQL (never Cypher), the trusted-service header contract, and the 503-means-absent degradation. Name kept — seed names are pinned by tests/unit/tool-registry-seed-idempotency.spec.ts.
 * 5 | maintainer@emeraldcoastsystemsgroup.com   | Same trap, sibling entry: opensearch-query disabled (enabled:false, defaultAuthMode 'off') and its copy rewritten to say so plainly. There is no OpenSearch/Elasticsearch anywhere in this stack, so an enabled auto-mode tool pointed every granted bot at $OPENSEARCH_URL. Disabled rather than deleted because the seeder only INSERTs — removing the entry would leave the stale enabled row in live tools tables with nothing left in the repo to explain it.
 */

import type { CreateToolInput } from '@/entities/tool';

/**
 * @description Baseline tool seed catalog registered by ToolRegistryService.
 * Extracted to preserve ToolRegistryService file-size and function-length constraints.
 */
export const TOOL_REGISTRY_BASELINE_TOOLS = [
      {
        name: 'execute_command',
        displayName: 'Shell Command',
        type: 'cli',
        category: 'system',
        version: '1.x',
        installSpec: { method: 'none' },
        skills: ['shell', 'command-execution', 'workspace-automation'],
        selectorFragment: 'Shell command execution is available only through explicit tool authorization.',
        routingTags: ['shell', 'command', 'automation'],
        authGroup: 'shell',
        defaultAuthMode: 'ask',
        description: 'Run shell commands in the task workspace. Commands require auth-mode enforcement before execution.',
        inputSchema: {
          type: 'object',
          properties: {
            command: { type: 'string' },
            timeoutMs: { type: 'integer' },
          },
          required: ['command'],
        },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use only for workspace-scoped command execution after approval or explicit auto authorization.',
        examples: [],
        requiresApproval: true,
        timeoutMs: 120000,
        tags: ['shell', 'command', 'system'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'presentron',
        displayName: 'Presentron',
        type: 'presentron',
        category: 'agent-integration',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['presentation', 'slide-generation'],
        selectorFragment: 'presentron',
        routingTags: ['presentron'],
        authGroup: 'agent-tools',
        defaultAuthMode: 'off',
        description: 'Render a real themed .pptx with the in-repo presentation engine (ten themes, twenty layouts). The deck is written into the task workspace.',
        inputSchema: {
          type: 'object',
          properties: {
            title: { type: 'string' },
            slides: {
              type: 'array',
              items: {
                type: 'object',
                properties: {
                  title: { type: 'string' },
                  content: { type: 'string' },
                  notes: { type: 'string' },
                  layout: { type: 'string' },
                },
              },
            },
            theme: { type: 'string' },
            subtitle: { type: 'string' },
            byline: { type: 'string' },
            outputPath: { type: 'string' },
          },
          required: ['slides'],
        },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Provide a deck title plus a slides array ({ title, content?, notes?, layout? }); the tool renders an editable PowerPoint into the task workspace and returns its path.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['presentron', 'presentation', 'pptx'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'rag-ingestion',
        displayName: 'RAG Ingestion',
        type: 'rag',
        category: 'agent-integration',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['rag', 'ingestion'],
        selectorFragment: 'rag-ingestion',
        routingTags: ['rag'],
        authGroup: 'agent-tools',
        defaultAuthMode: 'off',
        description: 'RAG Ingestion: API for ingesting documents into RAG system',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'See RAG ingestion documentation for usage.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['rag', 'ingestion'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'rag-query',
        displayName: 'RAG Query',
        type: 'rag',
        category: 'agent-integration',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['rag', 'retrieval', 'search'],
        selectorFragment: 'rag-query',
        routingTags: ['rag', 'search', 'retrieval'],
        authGroup: 'agent-tools',
        // Default ON for retrieval — RAG is read-only and grounding bot
        // output in real corpus content (instead of letting them invent
        // citations) is the whole point. Operators can flip back to off
        // per-agent via the cockpit if they want a specific bot to skip
        // retrieval for some reason.
        defaultAuthMode: 'auto',
        description: 'RAG Query: query the built-in ChromaDB-backed retrieval engine directly. Default collection for incident/build investigation is `infra-runbooks` (k8s troubleshooting, SRE overload patterns, Prometheus PromQL, k8s resource management).',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Before investigating an unfamiliar symptom, query the `infra-runbooks` collection for matching content. Cite results by doc_id + source_url from the returned metadata. Available collections are listed via /api/rag/collections.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['rag', 'query', 'retrieval'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'agent-scheduler',
        displayName: 'Agent Scheduler',
        type: 'api',
        category: 'automation',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['scheduling', 'recurring-automation', 'redis'],
        selectorFragment: 'Recurring self-scheduling is available through the /api/v1/agent schedule endpoints via execute_command.',
        routingTags: ['schedule', 'cron', 'automation', 'redis'],
        authGroup: 'scheduler',
        defaultAuthMode: 'off',
        description: 'Create, pause, resume, delete, and trigger recurring agent tasks backed by Redis schedule storage.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with curl against /api/v1/agent/schedule-task and /api/v1/agent/schedules endpoints.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['scheduler', 'redis', 'automation'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'aws-cli',
        displayName: 'AWS CLI',
        type: 'cli',
        category: 'cloud',
        version: '2.x',
        installSpec: { method: 'binary', verifyCommand: 'aws --version' },
        skills: ['aws', 'cloud-operations', 'iam', 's3'],
        selectorFragment: 'AWS CLI workflows are available through the shell when authorized.',
        routingTags: ['aws', 's3', 'iam', 'cloudformation'],
        authGroup: 'aws',
        defaultAuthMode: 'off',
        description: 'AWS command line tooling for cloud account inspection and operational tasks.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with aws subcommands when the environment is authorized.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['aws', 'cli', 'cloud'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'kubectl',
        displayName: 'kubectl',
        type: 'cli',
        category: 'kubernetes',
        version: '1.x',
        installSpec: { method: 'binary', verifyCommand: 'kubectl version --client' },
        skills: ['kubernetes', 'cluster-operations', 'deployment-debugging'],
        selectorFragment: 'Kubernetes cluster workflows are available through kubectl when authorized.',
        routingTags: ['kubernetes', 'kubectl', 'cluster'],
        authGroup: 'kubernetes',
        defaultAuthMode: 'off',
        description: 'Kubernetes CLI for cluster inspection, rollout management, and workload debugging.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with kubectl when cluster credentials are available.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['kubernetes', 'cli', 'devops'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'gcloud',
        displayName: 'Google Cloud CLI',
        type: 'cli',
        category: 'cloud',
        version: '1.x',
        installSpec: { method: 'binary', verifyCommand: 'gcloud --version' },
        skills: ['gcp', 'cloud-operations', 'artifact-registry'],
        selectorFragment: 'Google Cloud workflows are available through gcloud when authorized.',
        routingTags: ['gcp', 'gcloud', 'google-cloud'],
        authGroup: 'gcp',
        defaultAuthMode: 'off',
        description: 'Google Cloud CLI for infrastructure inspection and operational workflows.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with gcloud subcommands when the environment is authorized.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['gcp', 'cli', 'cloud'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'azure-cli',
        displayName: 'Azure CLI',
        type: 'cli',
        category: 'cloud',
        version: '2.x',
        installSpec: { method: 'binary', verifyCommand: 'az version' },
        skills: ['azure', 'cloud-operations', 'subscription-management'],
        selectorFragment: 'Azure workflows are available through az when authorized.',
        routingTags: ['azure', 'az', 'cloud'],
        authGroup: 'azure',
        defaultAuthMode: 'off',
        description: 'Azure CLI for resource group, subscription, and cloud operational workflows.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with az subcommands when Azure credentials are configured.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['azure', 'cli', 'cloud'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'helm',
        displayName: 'Helm',
        type: 'cli',
        category: 'kubernetes',
        version: '3.x',
        installSpec: { method: 'binary', verifyCommand: 'helm version --short' },
        skills: ['kubernetes', 'helm', 'release-management'],
        selectorFragment: 'Kubernetes package management workflows are available through Helm when authorized.',
        routingTags: ['helm', 'kubernetes', 'charts'],
        authGroup: 'kubernetes',
        defaultAuthMode: 'off',
        description: 'Helm CLI for chart rendering, release diffing, and deployment operations.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with helm for chart install/upgrade/template workflows.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['helm', 'kubernetes', 'cli'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'argocd',
        displayName: 'Argo CD CLI',
        type: 'cli',
        category: 'kubernetes',
        version: '2.x',
        installSpec: { method: 'binary', verifyCommand: 'argocd version --client --short' },
        skills: ['gitops', 'argocd', 'kubernetes-deployments'],
        selectorFragment: 'GitOps sync workflows are available through Argo CD CLI when authorized.',
        routingTags: ['argocd', 'gitops', 'kubernetes'],
        authGroup: 'kubernetes',
        defaultAuthMode: 'off',
        description: 'Argo CD CLI for app sync status, rollout health, and GitOps delivery controls.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with argocd for GitOps application operations.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['argocd', 'gitops', 'cli'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'terraform',
        displayName: 'Terraform CLI',
        type: 'cli',
        category: 'infrastructure',
        version: '1.x',
        installSpec: { method: 'binary', verifyCommand: 'terraform version' },
        skills: ['terraform', 'infrastructure-as-code', 'plan-review'],
        selectorFragment: 'Terraform workflows are available through the shell when authorized.',
        routingTags: ['terraform', 'iac', 'infrastructure'],
        authGroup: 'terraform',
        defaultAuthMode: 'off',
        description: 'Terraform CLI for plan inspection, drift detection, and infrastructure changes.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with terraform commands when the workspace contains Terraform configuration.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['terraform', 'cli', 'infrastructure'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'ansible',
        displayName: 'Ansible',
        type: 'cli',
        category: 'infrastructure',
        version: '2.x',
        installSpec: { method: 'binary', verifyCommand: 'ansible --version' },
        skills: ['ansible', 'configuration-management', 'automation'],
        selectorFragment: 'Ansible automation workflows are available through ansible/ansible-playbook when authorized.',
        routingTags: ['ansible', 'playbooks', 'automation'],
        authGroup: 'infrastructure',
        defaultAuthMode: 'off',
        description: 'Ansible CLI for infrastructure automation and configuration management playbooks.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with ansible or ansible-playbook for automation tasks.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['ansible', 'automation', 'cli'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'vault',
        displayName: 'Vault CLI',
        type: 'cli',
        category: 'security',
        version: '1.x',
        installSpec: { method: 'binary', verifyCommand: 'vault --version' },
        skills: ['vault', 'secrets-management', 'token-workflows'],
        selectorFragment: 'Secrets workflows are available through Vault CLI when authorized.',
        routingTags: ['vault', 'secrets', 'security'],
        authGroup: 'vault',
        defaultAuthMode: 'off',
        description: 'HashiCorp Vault CLI for secret lookup, auth, and policy workflows.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with vault when secret-store access is configured.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['vault', 'security', 'cli'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'git',
        displayName: 'Git',
        type: 'cli',
        category: 'scm',
        version: '2.x',
        installSpec: { method: 'binary', verifyCommand: 'git --version' },
        skills: ['git', 'branch-management', 'history-inspection'],
        selectorFragment: 'Source control workflows are available through git when authorized.',
        routingTags: ['git', 'commit', 'branch'],
        authGroup: 'scm',
        defaultAuthMode: 'off',
        description: 'Git CLI for repository history, branching, and local source control operations.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with git for local repository workflows.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['git', 'scm', 'cli'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'uv',
        displayName: 'uv',
        type: 'cli',
        category: 'development',
        version: '0.x',
        installSpec: { method: 'binary', verifyCommand: 'uv --version' },
        skills: ['python-packaging', 'virtualenv', 'mcp-runtime'],
        selectorFragment: 'Python package and MCP runtime workflows are available through uv when authorized.',
        routingTags: ['uv', 'python', 'mcp'],
        authGroup: 'development',
        defaultAuthMode: 'off',
        description: 'uv CLI for fast Python environment, package, and runtime management.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with uv for Python tool/runtime workflows.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['uv', 'python', 'cli'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'yq',
        displayName: 'yq',
        type: 'cli',
        category: 'data-processing',
        version: '4.x',
        installSpec: { method: 'binary', verifyCommand: 'yq --version' },
        skills: ['yaml-processing', 'manifest-transform'],
        selectorFragment: 'YAML transformation workflows are available through yq when authorized.',
        routingTags: ['yaml', 'yq', 'manifests'],
        authGroup: 'development',
        defaultAuthMode: 'off',
        description: 'yq CLI for querying and transforming YAML configuration/manifests.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with yq for YAML mutation and extraction tasks.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['yq', 'yaml', 'cli'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'gh',
        displayName: 'GitHub CLI',
        type: 'cli',
        category: 'scm',
        version: '2.x',
        installSpec: { method: 'binary', verifyCommand: 'gh --version' },
        skills: ['github', 'pull-requests', 'repository-operations'],
        selectorFragment: 'GitHub repository workflows are available through gh when authorized.',
        routingTags: ['github', 'gh', 'pull-request'],
        authGroup: 'github',
        defaultAuthMode: 'off',
        description: 'GitHub CLI for repository, issue, and pull request workflows.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with gh for GitHub automation when credentials are available.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['github', 'cli', 'scm'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'glab',
        displayName: 'GitLab CLI',
        type: 'cli',
        category: 'scm',
        version: '1.x',
        installSpec: { method: 'binary', verifyCommand: 'glab --version' },
        skills: ['gitlab', 'merge-requests', 'repository-operations'],
        selectorFragment: 'GitLab repository workflows are available through glab when authorized.',
        routingTags: ['gitlab', 'glab', 'merge-request'],
        authGroup: 'gitlab',
        defaultAuthMode: 'off',
        description: 'GitLab CLI for repository, issue, and merge request workflows.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with glab for GitLab automation when credentials are available.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['gitlab', 'cli', 'scm'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'docker',
        displayName: 'Docker CLI',
        type: 'cli',
        category: 'containers',
        version: '24.x',
        installSpec: { method: 'binary', verifyCommand: 'docker --version' },
        skills: ['docker', 'container-debugging', 'image-management'],
        selectorFragment: 'Container workflows are available through Docker CLI when authorized.',
        routingTags: ['docker', 'containers', 'images'],
        authGroup: 'containers',
        defaultAuthMode: 'off',
        description: 'Docker CLI for container inspection, image management, and local runtime debugging.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with docker subcommands when container runtime access is available.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['docker', 'cli', 'containers'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'docker-compose',
        displayName: 'Docker Compose',
        type: 'cli',
        category: 'containers',
        version: '2.x',
        installSpec: { method: 'binary', verifyCommand: 'docker compose version' },
        skills: ['compose', 'container-orchestration', 'service-debugging'],
        selectorFragment: 'Compose-based container workflows are available through docker compose when authorized.',
        routingTags: ['docker-compose', 'compose', 'containers'],
        authGroup: 'containers',
        defaultAuthMode: 'off',
        description: 'Docker Compose CLI for local multi-service stack management and diagnostics.',
        inputSchema: { type: 'object', properties: {} },
        outputSchema: { type: 'object', properties: {} },
        usageInstructions: 'Use execute_command with docker compose for stack lifecycle operations.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['docker', 'compose', 'cli'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'google-search',
        displayName: 'Google Search',
        type: 'api',
        category: 'research',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['web-search', 'research', 'information-retrieval'],
        selectorFragment: 'Web search is available through the Google Search integration when API credentials are configured.',
        routingTags: ['search', 'web', 'research', 'google'],
        authGroup: 'research',
        defaultAuthMode: 'off',
        description: 'Google Custom Search API integration for agent web research. Requires GOOGLE_SEARCH_API_KEY and GOOGLE_SEARCH_ENGINE_ID.',
        inputSchema: { type: 'object', properties: { query: { type: 'string' }, limit: { type: 'number' } } },
        outputSchema: { type: 'object', properties: { results: { type: 'array' } } },
        usageInstructions: 'Invoke via tool framework with a search query. Returns structured results with title, link, and snippet.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 30000,
        tags: ['google', 'search', 'research'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'gogcli',
        displayName: 'Google Workspace CLI',
        type: 'cli',
        category: 'workspace',
        version: '1.0.0',
        installSpec: { method: 'none', verifyCommand: 'node scripts/google-workspace-cli.js version' },
        skills: ['google-workspace', 'gmail', 'google-docs', 'google-sheets', 'google-slides', 'google-drive', 'calendar'],
        selectorFragment: 'Google Workspace automation is available through the repo-native Google Workspace CLI in the Google bot runtime when credentials are configured.',
        routingTags: ['gog', 'gogcli', 'google-workspace', 'gmail', 'google-docs', 'google-sheets', 'google-slides', 'google-drive'],
        authGroup: 'google-workspace',
        defaultAuthMode: 'off',
        description: 'Google Workspace CLI execution through the repo-native official Google API wrapper with persisted per-agent OAuth or service-account configuration and bot-scoped runtime state.',
        inputSchema: {
          type: 'object',
          properties: {
            command: { type: 'string' },
            args: { type: 'array', items: { type: 'string' } },
            json: { type: 'boolean' },
            timeoutMs: { type: 'number' },
          },
        },
        outputSchema: { type: 'object', properties: { stdout: { type: 'string' }, stderr: { type: 'string' } } },
        usageInstructions: 'Use the Google Workspace CLI runtime to access Gmail, Docs, Sheets, Drive, Slides, Calendar, and related Google Workspace APIs from the Google bot.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 120000,
        tags: ['google', 'workspace', 'gogcli', 'gmail', 'docs', 'sheets', 'slides'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'finance-import',
        displayName: 'Finance Import',
        type: 'api',
        category: 'finance',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['finance', 'data-import', 'ledger-management'],
        selectorFragment: 'Personal finance transaction import is available for CSV, JSON, and inline transaction payloads.',
        routingTags: ['finance-import', 'transactions', 'ledger', 'budget'],
        authGroup: 'finance',
        defaultAuthMode: 'off',
        description: 'Import transactions into the personal-finance bot ledger from workspace files or inline payloads.',
        inputSchema: {
          type: 'object',
          properties: {
            path: { type: 'string' },
            paths: { type: 'array', items: { type: 'string' } },
            source: { type: 'string' },
            transactions: { type: 'array', items: { type: 'object' } },
          },
        },
        outputSchema: { type: 'object', properties: { importedCount: { type: 'number' }, totalTransactions: { type: 'number' } } },
        usageInstructions: 'Load personal finance data before analysis. Supports workspace-local CSV/JSON files and inline transaction arrays.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['finance', 'import', 'ledger'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'finance-report',
        displayName: 'Finance Report',
        type: 'api',
        category: 'finance',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['finance', 'reporting', 'budgeting'],
        selectorFragment: 'Personal finance reporting and Markdown report generation are available through the finance-report tool.',
        routingTags: ['finance-report', 'budget-report', 'spending-report'],
        authGroup: 'finance',
        defaultAuthMode: 'off',
        description: 'Generate Markdown personal finance reports with category, merchant, and budget summaries.',
        inputSchema: {
          type: 'object',
          properties: {
            title: { type: 'string' },
            category: { type: 'string' },
            lookbackDays: { type: 'number' },
            alertThreshold: { type: 'number' },
            outputPath: { type: 'string' },
          },
        },
        outputSchema: { type: 'object', properties: { reportPath: { type: 'string' }, reportMarkdown: { type: 'string' } } },
        usageInstructions: 'Use after importing transactions to generate a detailed Markdown report into the active workspace.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['finance', 'report', 'budget'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'analyze-spending',
        displayName: 'Analyze Spending',
        type: 'api',
        category: 'finance',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['finance', 'analytics', 'spend-analysis'],
        selectorFragment: 'Spend trend and merchant/category analysis are available through the analyze-spending tool.',
        routingTags: ['analyze-spending', 'spend-analysis', 'merchant-analysis'],
        authGroup: 'finance',
        defaultAuthMode: 'off',
        description: 'Analyze imported personal finance transactions for category totals, merchant concentration, and unusual activity.',
        inputSchema: {
          type: 'object',
          properties: {
            category: { type: 'string' },
            lookbackDays: { type: 'number' },
            alertThreshold: { type: 'number' },
          },
        },
        outputSchema: { type: 'object', properties: { totalSpend: { type: 'number' } } },
        usageInstructions: 'Use after finance-import to understand category trends, top merchants, and unusual transactions.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['finance', 'analysis', 'spending'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'check-budget',
        displayName: 'Check Budget',
        type: 'api',
        category: 'finance',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['finance', 'budgeting', 'variance-analysis'],
        selectorFragment: 'Budget-versus-actual checks are available through the check-budget tool.',
        routingTags: ['check-budget', 'budget', 'variance'],
        authGroup: 'finance',
        defaultAuthMode: 'off',
        description: 'Compare imported transactions against configured budget targets and surface over-budget categories.',
        inputSchema: {
          type: 'object',
          properties: {
            category: { type: 'string' },
            lookbackDays: { type: 'number' },
            alertThreshold: { type: 'number' },
          },
        },
        outputSchema: { type: 'object', properties: { budgetStatus: { type: 'array' } } },
        usageInstructions: 'Use after finance-import to review budget adherence and variance against target amounts.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 60000,
        tags: ['finance', 'budget', 'analysis'],
        enabled: true,
        registeredBy: 'system',
      },
      {
        name: 'knowledge-enhancement',
        displayName: 'Knowledge Enhancement',
        type: 'api',
        category: 'research',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['research', 'knowledge-gap-analysis', 'rag-ingestion'],
        selectorFragment: 'Autonomous knowledge enhancement is available for filling knowledge gaps via web research and RAG ingestion.',
        routingTags: ['knowledge', 'enhancement', 'research', 'rag'],
        authGroup: 'research',
        defaultAuthMode: 'off',
        description: 'Autonomous research loop: analyze gaps, search web, ingest into ChromaDB. Requires Google Search credentials.',
        inputSchema: { type: 'object', properties: { queries: { type: 'array', items: { type: 'string' } } } },
        outputSchema: { type: 'object', properties: { runId: { type: 'string' }, documentsIngested: { type: 'number' } } },
        usageInstructions: 'Invoke with an array of research queries. Each query triggers web search and RAG ingestion.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 120000,
        tags: ['knowledge', 'research', 'rag'],
        enabled: true,
        registeredBy: 'system',
      },
      // ── Graph & Data Platform Tools ────────────────────────────────────────
      {
        name: 'graph-query',
        displayName: 'Graph Query (caller-scoped /api/graph)',
        type: 'api',
        category: 'data-platform',
        version: '2.0.0',
        installSpec: { method: 'none' },
        skills: ['graph-query', 'topology', 'correlation', 'rca'],
        selectorFragment: "Graph traversal is available over the swarm's own caller-scoped /api/graph route (ADR-045): AQL reads, neighbors, shortest path, and node/edge upsert against the caller's OWN graph.",
        routingTags: ['graph', 'topology', 'correlation', 'rca', 'aql', 'arangodb'],
        authGroup: 'data-platform',
        defaultAuthMode: 'auto',
        description:
          "Read and write the caller's OWN graph through the platform's caller-scoped /api/graph route (ADR-045). " +
          'The engine is ArangoDB and the query language is AQL — NOT Cypher and NOT Gremlin. There is no GRAPH_API_URL ' +
          'and no direct database access: the route resolves the graph from the caller identity, so a bot can never ' +
          "reach another person's graph. The tier is OPTIONAL — when the deployment has no graph engine every endpoint " +
          'returns HTTP 503, which is a supported state to note once and skip, not an error to retry.',
        inputSchema: {
          type: 'object',
          properties: {
            aql: { type: 'string', description: 'AQL read query (collections are literally `nodes` and `edges`; filter on the `id` field, never `_key`)' },
            bindVars: { type: 'object', description: 'AQL bind variables' },
          },
          required: ['aql'],
        },
        outputSchema: { type: 'object', properties: { rows: { type: 'array' }, nodes: { type: 'array' } } },
        usageInstructions:
          'Use execute_command with curl against the api, sending the trusted-service headers so the route resolves ' +
          "the right person's graph:\n" +
          '  READ (AQL, read-only — a data-modifying query is refused with HTTP 400 graph_read_only):\n' +
          '    curl -s -X POST "http://oshal-local-api:5000/api/graph/query" \\\n' +
          '      -H "X-Service-Secret: $SWARM_SERVICE_SECRET" -H "X-OSHAL-User-Sub: $OSHAL_USER_SUB" \\\n' +
          '      -H "Content-Type: application/json" \\\n' +
          '      -d \'{"aql":"FOR n IN nodes FILTER @l IN n.labels RETURN n.id","bindVars":{"l":"service"}}\'\n' +
          '  NEIGHBORS (blast radius): GET /api/graph/neighbors?id=<nodeId>&depth=<1-6>\n' +
          '  PATH:                     GET /api/graph/path?from=<nodeId>&to=<nodeId>\n' +
          '  WRITE:                    POST /api/graph/nodes {"nodes":[{"id","labels","props"}]}\n' +
          '                            POST /api/graph/edges {"edges":[{"from","to","type","props"}]}\n' +
          'HTTP 503 means no graph engine on this deployment — report it once and continue without the graph.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 30000,
        tags: ['graph', 'aql', 'arangodb', 'topology', 'data-platform'],
        enabled: true,
        registeredBy: 'system',
        // ui: { sidebarIcon: 'codicon codicon-type-hierarchy', sidebarLabel: 'Graph Viewer', route: 'tool-graph-query' },
        // TODO: Enable tool UI after DB migration adds ui column to tools table
      },
      {
        name: 'opensearch-query',
        displayName: 'OpenSearch / Elasticsearch Query (no cluster in this stack)',
        type: 'api',
        category: 'data-platform',
        version: '2.0.0',
        installSpec: { method: 'none' },
        skills: ['opensearch', 'elasticsearch', 'log-search', 'event-query'],
        selectorFragment: 'No OpenSearch/Elasticsearch cluster is part of this platform — do not offer log search over one.',
        routingTags: ['opensearch', 'elasticsearch', 'logs', 'search', 'events'],
        authGroup: 'data-platform',
        // DISABLED, not deleted: the name is pinned by tests/unit/tool-registry-seed-idempotency.spec.ts
        // (seed names are the contract), and the row already exists in every live tools table — the
        // seeder only INSERTs, so a delete here would leave the stale enabled row behind forever.
        // There is no OpenSearch anywhere in this stack (the compose file strips it; see
        // dispatch-incident-worker.ts change-log entry 2), so an enabled tool with defaultAuthMode
        // 'auto' was instructing every granted bot to curl $OPENSEARCH_URL — a variable nothing sets.
        defaultAuthMode: 'off',
        description:
          'RETIRED — there is no OpenSearch or Elasticsearch cluster in this platform. The compose stack ' +
          'never ships one and OPENSEARCH_URL is set nowhere, so any curl against it fails to resolve. ' +
          'Log/event search is not a capability this deployment has; use the ticket evidence, the workspace ' +
          'files, and the RAG corpus (/api/rag/search) instead. Kept as a disabled row only because the ' +
          'seeder inserts and never updates, so deleting the entry would orphan the stale row already in ' +
          'live tools tables.',
        inputSchema: {
          type: 'object',
          properties: {
            index: { type: 'string', description: 'Index pattern to query' },
            query: { type: 'object', description: 'OpenSearch/ES DSL query body' },
            size: { type: 'number', description: 'Number of results to return' },
          },
          required: ['index', 'query'],
        },
        outputSchema: { type: 'object', properties: { hits: { type: 'object' }, aggregations: { type: 'object' } } },
        usageInstructions: 'Do not use — no OpenSearch/Elasticsearch endpoint exists on this deployment. Use /api/rag/search for corpus retrieval and read the ticket + workspace evidence for incident data.',
        examples: [],
        requiresApproval: false,
        timeoutMs: 30000,
        tags: ['opensearch', 'elasticsearch', 'search', 'data-platform', 'retired'],
        enabled: false,
        registeredBy: 'system',
      },
      {
        name: 'nats-publish',
        displayName: 'NATS Publish',
        type: 'api',
        category: 'messaging',
        version: '1.0.0',
        installSpec: { method: 'none' },
        skills: ['nats', 'event-publish', 'streaming', 'messaging'],
        selectorFragment: 'NATS JetStream publishing is available for emitting events and messages via $NATS_URL.',
        routingTags: ['nats', 'jetstream', 'publish', 'events', 'messaging'],
        authGroup: 'messaging',
        defaultAuthMode: 'ask',
        description: 'Publish messages to a NATS JetStream instance (configured via NATS_URL env var). Used for emitting events, status updates, and inter-service messages.',
        inputSchema: {
          type: 'object',
          properties: {
            subject: { type: 'string', description: 'NATS subject to publish to' },
            payload: { type: 'object', description: 'JSON message payload' },
          },
          required: ['subject', 'payload'],
        },
        outputSchema: { type: 'object', properties: { ack: { type: 'boolean' }, seq: { type: 'number' } } },
        usageInstructions: 'Use execute_command with nats CLI or curl against NATS HTTP gateway at $NATS_URL. Publish JSON payloads to JetStream subjects for downstream processing.',
        examples: [],
        requiresApproval: true,
        timeoutMs: 10000,
        tags: ['nats', 'publish', 'messaging'],
        enabled: true,
        registeredBy: 'system',
      },
] as unknown as CreateToolInput[];
