/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * SEQ                 | AUTHOR                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 1 | maintainer@emeraldcoastsystemsgroup.com   | Extracted from seed-tools.ts (1000-line cap decomposition): System utility tool definitions (bash, curl, wget, make, openssh-client, openssl, tar, gzip, unzip, sqlite, graphviz, fzf)
 */

import { ToolType, AuthMode, InstallMethod } from '../../src/shared/types/tool';
import type { CreateToolInput } from '../../src/entities/tool/schemas/tool-schemas';

/**
 * @description System utility tool definitions (bash, curl, wget, make, openssh-client,
 * openssl, tar, gzip, unzip, sqlite, graphviz, fzf) — part of the seed catalog aligned
 * with the any-bot/Dockerfile baseline image.
 */
export const systemUtilityTools: CreateToolInput[] = [
  {
    name: 'bash',
    displayName: 'Bash Shell',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '5.2',
    description: 'Bourne Again Shell for script execution',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'bash --version',
    },
    skills: ['shell', 'scripting', 'automation'],
    selectorFragment: 'Bash shell script execution and automation',
    routingTags: ['bash', 'shell', 'scripting'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        script: { type: 'string', description: 'Bash script to execute' },
      },
      required: ['script'],
    },
    usageInstructions: 'Use Bash to execute shell scripts and commands.',
    examples: [
      { command: 'bash script.sh', description: 'Execute a shell script' },
    ],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['shell', 'utilities', 'scripting'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'curl',
    displayName: 'cURL',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '8.5.0',
    description: 'Command-line tool for transferring data with URLs',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'curl --version',
    },
    skills: ['http', 'api', 'data-transfer', 'web'],
    selectorFragment: 'HTTP requests and data transfer with URLs',
    routingTags: ['curl', 'http', 'api', 'web'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'URL to request' },
        method: { type: 'string', description: 'HTTP method' },
        headers: { type: 'object', description: 'HTTP headers' },
      },
      required: ['url'],
    },
    usageInstructions: 'Use curl to make HTTP requests and transfer data.',
    examples: [
      { command: 'curl https://api.example.com', description: 'GET request' },
      { command: 'curl -X POST -d \'data\' https://api.example.com', description: 'POST request' },
    ],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['http', 'utilities', 'api'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'wget',
    displayName: 'Wget',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '1.21',
    description: 'Network utility to retrieve files from the web',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'wget --version',
    },
    skills: ['download', 'http', 'ftp', 'web'],
    selectorFragment: 'Download files from web servers via HTTP/HTTPS/FTP',
    routingTags: ['wget', 'download', 'http', 'web'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        url: { type: 'string', description: 'URL to download' },
        output: { type: 'string', description: 'Output file path' },
      },
      required: ['url'],
    },
    usageInstructions: 'Use wget to download files from web servers.',
    examples: [
      { command: 'wget https://example.com/file.zip', description: 'Download a file' },
    ],
    requiresApproval: false,
    timeoutMs: 300000,
    tags: ['download', 'utilities', 'web'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'make',
    displayName: 'Make',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '4.4',
    description: 'Build automation tool that builds executable programs from source',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'make --version',
    },
    skills: ['build', 'automation', 'compilation'],
    selectorFragment: 'Build automation and Makefile execution',
    routingTags: ['make', 'build', 'automation'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        target: { type: 'string', description: 'Make target to build' },
        makefile: { type: 'string', description: 'Path to Makefile' },
      },
    },
    usageInstructions: 'Use make to build projects using Makefiles.',
    examples: [
      { command: 'make all', description: 'Build all targets' },
      { command: 'make clean', description: 'Clean build artifacts' },
    ],
    requiresApproval: false,
    timeoutMs: 300000,
    tags: ['build', 'utilities', 'automation'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'openssh-client',
    displayName: 'OpenSSH Client',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '9.6',
    description: 'Secure Shell client for remote login',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'ssh -V',
    },
    skills: ['ssh', 'remote-access', 'security'],
    selectorFragment: 'Secure remote server access via SSH',
    routingTags: ['ssh', 'remote', 'security'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.ASK,
    inputSchema: {
      type: 'object',
      properties: {
        host: { type: 'string', description: 'Remote host to connect to' },
        user: { type: 'string', description: 'Username for SSH connection' },
      },
      required: ['host'],
    },
    usageInstructions: 'Use SSH to securely connect to remote servers.',
    examples: [
      { command: 'ssh user@host', description: 'Connect to remote server' },
    ],
    requiresApproval: true,
    timeoutMs: 120000,
    tags: ['ssh', 'utilities', 'security'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'openssl',
    displayName: 'OpenSSL',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '3.1',
    description: 'Cryptography and SSL/TLS toolkit',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'openssl version',
    },
    skills: ['encryption', 'ssl', 'tls', 'certificates'],
    selectorFragment: 'Cryptographic operations, SSL/TLS, and certificate management',
    routingTags: ['openssl', 'encryption', 'ssl', 'certificates'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        command: { type: 'string', description: 'OpenSSL command to execute' },
      },
      required: ['command'],
    },
    usageInstructions: 'Use OpenSSL for encryption, decryption, and certificate operations.',
    examples: [
      { command: 'openssl version', description: 'Show OpenSSL version' },
      { command: 'openssl x509 -in cert.pem -text', description: 'Display certificate details' },
    ],
    requiresApproval: false,
    timeoutMs: 30000,
    tags: ['encryption', 'utilities', 'security'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'tar',
    displayName: 'Tar',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '1.34',
    description: 'Archive utility for creating and extracting tar files',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'tar --version',
    },
    skills: ['archive', 'compression', 'backup'],
    selectorFragment: 'Create and extract tar archive files',
    routingTags: ['tar', 'archive', 'compression'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        operation: { type: 'string', description: 'Tar operation (create, extract, list)' },
        file: { type: 'string', description: 'Archive file path' },
      },
      required: ['operation', 'file'],
    },
    usageInstructions: 'Use tar to create and extract archive files.',
    examples: [
      { command: 'tar -czf archive.tar.gz dir/', description: 'Create compressed archive' },
      { command: 'tar -xzf archive.tar.gz', description: 'Extract compressed archive' },
    ],
    requiresApproval: false,
    timeoutMs: 180000,
    tags: ['archive', 'utilities', 'compression'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'gzip',
    displayName: 'Gzip',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '1.12',
    description: 'File compression utility',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'gzip --version',
    },
    skills: ['compression', 'decompression'],
    selectorFragment: 'Compress and decompress files with gzip',
    routingTags: ['gzip', 'compression', 'archive'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        file: { type: 'string', description: 'File to compress or decompress' },
        decompress: { type: 'boolean', description: 'Decompress instead of compress' },
      },
      required: ['file'],
    },
    usageInstructions: 'Use gzip to compress or decompress files.',
    examples: [
      { command: 'gzip file.txt', description: 'Compress a file' },
      { command: 'gzip -d file.txt.gz', description: 'Decompress a file' },
    ],
    requiresApproval: false,
    timeoutMs: 120000,
    tags: ['compression', 'utilities'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'unzip',
    displayName: 'Unzip',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '6.0',
    description: 'Extract compressed files from ZIP archives',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'unzip -v',
    },
    skills: ['archive', 'extraction', 'zip'],
    selectorFragment: 'Extract files from ZIP archives',
    routingTags: ['unzip', 'zip', 'archive', 'extraction'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        file: { type: 'string', description: 'ZIP file to extract' },
        destination: { type: 'string', description: 'Destination directory' },
      },
      required: ['file'],
    },
    usageInstructions: 'Use unzip to extract ZIP archives.',
    examples: [
      { command: 'unzip archive.zip', description: 'Extract ZIP archive' },
      { command: 'unzip archive.zip -d /dest', description: 'Extract to specific directory' },
    ],
    requiresApproval: false,
    timeoutMs: 120000,
    tags: ['zip', 'utilities', 'archive'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'sqlite',
    displayName: 'SQLite',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '3.44',
    description: 'Command-line interface for SQLite database',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'sqlite3 --version',
    },
    skills: ['database', 'sql', 'data-storage'],
    selectorFragment: 'SQLite database operations and SQL queries',
    routingTags: ['sqlite', 'database', 'sql'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        database: { type: 'string', description: 'SQLite database file' },
        query: { type: 'string', description: 'SQL query to execute' },
      },
      required: ['database', 'query'],
    },
    usageInstructions: 'Use SQLite CLI to interact with SQLite databases.',
    examples: [
      { command: 'sqlite3 db.sqlite "SELECT * FROM users"', description: 'Execute SQL query' },
    ],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['database', 'utilities', 'sql'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'graphviz',
    displayName: 'Graphviz',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '9.0',
    description: 'Graph visualization software for creating diagrams',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'dot -V',
    },
    skills: ['visualization', 'diagrams', 'graphs'],
    selectorFragment: 'Create diagrams and graph visualizations',
    routingTags: ['graphviz', 'dot', 'visualization', 'diagrams'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        input: { type: 'string', description: 'DOT file input' },
        output: { type: 'string', description: 'Output image file' },
        format: { type: 'string', description: 'Output format (png, svg, pdf)' },
      },
      required: ['input', 'output'],
    },
    usageInstructions: 'Use Graphviz to create diagrams from DOT language files.',
    examples: [
      { command: 'dot -Tpng input.dot -o output.png', description: 'Generate PNG diagram' },
    ],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['visualization', 'utilities', 'diagrams'],
    enabled: true,
    registeredBy: 'system',
  },
  {
    name: 'fzf',
    displayName: 'fzf',
    type: ToolType.CLI,
    category: 'system-utilities',
    version: '0.46',
    description: 'Command-line fuzzy finder for interactive filtering',
    installSpec: {
      method: InstallMethod.NONE,
      verifyCommand: 'fzf --version',
    },
    skills: ['fuzzy-search', 'filtering', 'interactive'],
    selectorFragment: 'Interactive fuzzy finder for command-line filtering',
    routingTags: ['fzf', 'fuzzy-search', 'filter', 'interactive'],
    authGroup: 'utilities',
    defaultAuthMode: AuthMode.AUTO,
    inputSchema: {
      type: 'object',
      properties: {
        input: { type: 'string', description: 'Input to filter' },
      },
    },
    usageInstructions: 'Use fzf for interactive fuzzy searching and filtering.',
    examples: [
      { command: 'ls | fzf', description: 'Fuzzy search directory listing' },
    ],
    requiresApproval: false,
    timeoutMs: 60000,
    tags: ['fuzzy-search', 'utilities', 'interactive'],
    enabled: true,
    registeredBy: 'system',
  },
];
