/**
 * CHANGE LOG
 * -----------------------------------------------------------------------------
 * SEQ                 | AUTHOR                      | DESCRIPTION
 * -----------------------------------------------------------------------------
 * 1 | maintainer@emeraldcoastsystemsgroup.com   | Documented native GitHub Issues ticket intake, trusted feed routing, and optional no-history REST reconciliation
 * 2 | maintainer@emeraldcoastsystemsgroup.com   | Clarified that free REST recovery reconciles missed issue lifecycle updates
 */

/**
 * Generate Markdown docs for every connector.yaml (ADR-065 Phase 3).
 *
 * Usage: npx ts-node --transpile-only scripts/connectors/gen-connector-docs.ts
 * Reads swarm-apps/connectors/*.yaml, writes docs/connectors/<provider>.md via specToMarkdown.
 * Also prints the catalog audit so docs and the gate run together.
 *
 * @module scripts/connectors/gen-connector-docs
 */
import { mkdirSync, readdirSync, writeFileSync } from 'fs';
import { join } from 'path';
import { loadConnectorSpec, type ConnectorSpec } from '../../src/app/connectors/runtime/spec';
import { specToMarkdown } from '../../src/app/connectors/runtime/spec-to-doc';
import { auditConnectorCatalog, formatAudit } from '../../src/app/connectors/runtime/catalog-audit';

const root = process.cwd();
const specDir = join(root, 'swarm-apps/connectors');
const outDir = join(root, 'docs/connectors');
mkdirSync(outDir, { recursive: true });

const files = readdirSync(specDir).filter((f) => f.endsWith('.yaml') || f.endsWith('.yml'));
const specs: ConnectorSpec[] = [];
for (const f of files) {
  const spec = loadConnectorSpec(join(specDir, f));
  specs.push(spec);
  writeFileSync(join(outDir, `${spec.provider}.md`), specToMarkdown(spec));
}
specs.sort((a, b) => a.provider.localeCompare(b.provider));
// eslint-disable-next-line no-console
console.log(`wrote ${specs.length} docs/connectors/*.md`);

// Auto-build the catalog README so the index never drifts from the specs.
const authLabel = (s: ConnectorSpec): string => {
  const a = s.auth;
  if (a.type === 'oauth2') return s.credProvider ? `oauth2 (→${s.credProvider})` : 'oauth2';
  if (a.type === 'apiKeyHeader') return `apiKey (header ${a.header})`;
  if (a.type === 'apiKeyQuery') return `apiKey (query ${a.param})`;
  if (a.type === 'basic') return 'basic';
  return 'none';
};
const pageLabel = (s: ConnectorSpec): string => (s.pagination ? s.pagination.strategy : '—');
const hook = (s: ConnectorSpec): string => (s.webhooks?.length ? ' + webhook' : '');
const rows = specs.map((s) => `| ${s.displayName || s.provider} | \`${s.provider}\` | ${authLabel(s)} | ${pageLabel(s)}${hook(s)} | [${s.provider}.md](${s.provider}.md) |`).join('\n');

const readme = `# Connector catalog (ADR-065)

> Auto-generated by \`scripts/connectors/gen-connector-docs.ts\` — do not edit by hand; change the specs.
> ${specs.length} declarative connectors, each a \`swarm-apps/connectors/<provider>.yaml\` built into a
> live client by the runtime (no per-connector HTTP code). See [ADR-065](../adr/065-connector-runtime-and-spec.md),
> [spec guide](../connector-spec.md), and the [RUNBOOK](RUNBOOK.md) to enable/connect/verify.

## Adding a connector
1. Write \`swarm-apps/connectors/<provider>.yaml\` (or draft from an OpenAPI doc via \`specFromOpenApi\`).
2. Run this script — regenerates docs + this index, and runs the audit gate (0 errors required).
3. Auto-mounts at \`/api/connectors/<provider>\` (\`CONNECTOR_SPEC_ROUTES=on\`); connect a token via
   \`/api/connect/<provider>/token\` (paste) or \`CONNECTOR_<PROVIDER>_TOKEN\` env. Broker token wins.

## Catalog (${specs.length})
| Connector | Provider | Auth | Pagination | Doc |
| --- | --- | --- | --- | --- |
${rows}

## Webhooks
Connectors may declare \`webhooks:\` (verified inbound events) → mounted at
\`/api/hooks/:provider/:event\` (verify → dedup via \`oshal_webhook_deliveries\` → swarm ticket), behind
\`CONNECTOR_WEBHOOKS\`.

GitHub ticket intake uses the native \`issues\` webhook at
\`POST /api/hooks/github/issues\`. GitHub sends the event directly to OSHAL; this does not require a
workflow file, a GitHub Actions runner, or billable Actions minutes. The endpoint verifies
\`X-Hub-Signature-256\`, deduplicates delivery, allowlists configured repositories, and projects each
new request into \`backlog\` with a stable \`owner/repository#number\` external id.

### Default GitHub ticket feeds

| Feed | Issue repository | Work repository | Release repository | OSHAL queue | Ticket type |
| --- | --- | --- | --- | --- | --- |
| Applications | \`emeraldcoastsystemsgroup/oshal-applications\` | \`emeraldcoastsystemsgroup/oshal-applications\` | \`emeraldcoastsystemsgroup/oshal-applications\` | GitHub Application Requests | \`build\` |
| Core (preferred) | \`emeraldcoastsystemsgroup/open-shal\` | \`emeraldcoastsystemsgroup/open-shal\` | \`emeraldcoastsystemsgroup/oshal\` | GitHub Core Requests | \`oshal-dev\` |
| Core (release compatibility) | \`emeraldcoastsystemsgroup/oshal\` | \`emeraldcoastsystemsgroup/open-shal\` | \`emeraldcoastsystemsgroup/oshal\` | GitHub Core Requests | \`oshal-dev\` |

All three feeds are request-only and enforce their configured bootstrap boundary: existing history before
the cutover is not imported. Override the trusted mapping with \`GITHUB_TICKET_FEEDS\` when needed.
An optional read-only REST pull using \`GITHUB_TICKET_TOKEN\` provides cursor-backed reconciliation,
including missed close and reopen updates; it is not the primary intake path and also requires no
GitHub Actions job.

Public routing and closure semantics are documented in
[Requests and defects](../operations/requests-and-defects.md).
`;
writeFileSync(join(outDir, 'README.md'), readme);
// eslint-disable-next-line no-console
console.log('wrote docs/connectors/README.md');

// eslint-disable-next-line no-console
console.log('\nCatalog audit:\n' + formatAudit(auditConnectorCatalog(specDir)));
