"""Generate docs/OPERATOR-QUEUE.md — everything that is waiting on the operator.

Derived from docs/backlog/triage-2026-09-15.json plus the live docs/BACKLOG.md, so it cannot drift
the way a hand-typed list would. Entries whose heading is gone, or whose body records that they
were built or met, are dropped automatically.

Run: python scripts/gen-operator-queue.py
"""
import io, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__))) if '__file__' in dir() else '.'
LEDGER = os.path.join('docs', 'backlog', 'triage-2026-09-15.json')
BACKLOG = os.path.join('docs', 'BACKLOG.md')
OUT = os.path.join('docs', 'OPERATOR-QUEUE.md')

led = json.load(io.open(LEDGER, encoding='utf-8'))
items = led if isinstance(led, list) else (led.get('entries') or led.get('items') or [])
bl = io.open(BACKLOG, encoding='utf-8', newline='').read()

bodies = {}
for chunk in re.split(r'(?m)^### ', bl)[1:]:
    bodies[chunk.split('\n')[0].strip()] = chunk

CLOSED = re.compile(r'Built 2026-09-1[67]|Done when:\*\* met')


def still_open(entry):
    body = bodies.get(entry['title'])
    if body is None:
        return False          # heading gone -> closed
    return not CLOSED.search(body)


def section_of(entry):
    return (entry.get('section') or 'Other').strip()


def rows(verdict):
    picked = [i for i in items if i.get('verdict') == verdict and still_open(i)]
    picked.sort(key=lambda i: (section_of(i), i['title']))
    return picked


def clean(text):
    return ' '.join((text or '').split())


decisions = rows('operator')
proofs = rows('live-proof')

NOW = os.path.join('docs', 'backlog', 'operator-now.json')
now = json.load(io.open(NOW, encoding='utf-8')) if os.path.exists(NOW) else {'items': []}

lines = []
w = lines.append
w('# Operator queue')
w('')
w('**Everything waiting on a human.** Generated by `scripts/gen-operator-queue.py` from')
w('`docs/backlog/triage-2026-09-15.json` and the live `docs/BACKLOG.md` — do not hand-edit, it will')
w('be overwritten. An entry disappears from this file automatically once its backlog heading is gone')
w('or its body records that it was built.')
w('')
w('Counts are generated, never typed: **%d decisions**, **%d live proofs**.' % (len(decisions), len(proofs)))
w('')
w('To comment, write under an entry in this file and tell me, or just say the entry name.')
w('')
w('---')
w('')
w('## Right now — %d' % len(now.get('items', [])))
w('')
w('Short-lived and blocking today. Source: `docs/backlog/operator-now.json` (as of %s).' % now.get('asOf', '?'))
w('')
for it in now.get('items', []):
    w('### %s' % it['title'])
    w('')
    w(clean(it.get('why')))
    w('')
    w('**Do:** %s' % clean(it.get('how')))
    w('')
w('---')
w('')
w('## Decisions — %d' % len(decisions))
w('')
w('Each of these is blocked on a judgement only you can make. No code is waiting on anything else.')
w('')
cur = None
for e in decisions:
    sec = section_of(e)
    if sec != cur:
        cur = sec
        w('')
        w('### %s' % sec)
        w('')
    size = e.get('size') or '?'
    repo = e.get('repo') or '?'
    w('- **%s** *(%s, %s)*' % (e['title'], size, repo))
    ask = clean(e.get('operatorAsk'))
    if ask:
        w('  %s' % ask)
w('')
w('---')
w('')
w('## Live proofs — %d' % len(proofs))
w('')
w('These are built and guarded but unproven in the real world. Each needs a real run, a real')
w('credential, a second machine, or a real device — something no test can stand in for.')
w('')
cur = None
for e in proofs:
    sec = section_of(e)
    if sec != cur:
        cur = sec
        w('')
        w('### %s' % sec)
        w('')
    w('- **%s**' % e['title'])
    ask = clean(e.get('operatorAsk'))
    if ask:
        w('  %s' % ask)
w('')

io.open(OUT, 'w', encoding='utf-8', newline='\n').write('\n'.join(lines) + '\n')
print('wrote %s — %d decisions, %d live proofs' % (OUT, len(decisions), len(proofs)))
