#!/bin/bash
# =============================================================================
# CHANGE LOG
# -----------------------------------------------------------------------------
# SEQ | AUTHOR                                      | DESCRIPTION
# -----------------------------------------------------------------------------
# 1   | maintainer@emeraldcoastsystemsgroup.com     | Initial implementation - Cline CLI auth setup for oshal
# 2   | maintainer@emeraldcoastsystemsgroup.com     | Use LLM_PROVIDER env var, preserve existing OAuth tokens on PVC
# 3   | maintainer@emeraldcoastsystemsgroup.com     | Scrubbed retired legacy product references (provider name is noop; narration removed)
# 4   | maintainer@emeraldcoastsystemsgroup.com     | SEC-05 closure: make startup configuration non-secret and plan-only, disable all automatic/MCP actions, and tombstone legacy runtime credentials instead of preserving or manufacturing OAuth state.
# =============================================================================
#
# @description Writes only non-secret compatibility metadata for the registered Cline
# interface. Unattended Cline execution is disabled by the kernel until an audited
# OSHAL-brokered sandbox exists. OAuth/API credentials stay in vendor/server-owned
# stores and must never be copied into ~/.cline or printed by this script.
#
# Usage: bash scripts/setup-cline-auth.sh

set -eu

CLINE_HOME_DIR="${HOME:-/root}/.cline"
CLINE_DATA_DIR="${CLINE_HOME_DIR}/data"
CLINE_PROVIDER="${LLM_PROVIDER:-noop}"
CLINE_MODEL="${LLM_MODEL:-disabled}"

# Provider/model values are compatibility metadata, not shell or JSON programs.
case "${CLINE_PROVIDER}" in
  ''|*[!A-Za-z0-9._-]*) CLINE_PROVIDER='noop' ;;
esac
case "${CLINE_MODEL}" in
  ''|*[!A-Za-z0-9._:/-]*) CLINE_MODEL='disabled' ;;
esac

umask 077
mkdir -p "${CLINE_DATA_DIR}" "${CLINE_HOME_DIR}/data/settings"

cat > "${CLINE_HOME_DIR}/config.json" <<EOF
{
  "provider": "${CLINE_PROVIDER}",
  "model": "${CLINE_MODEL}",
  "autoApprove": false
}
EOF

cat > "${CLINE_DATA_DIR}/globalState.json" <<EOF
{
  "welcomeViewCompleted": true,
  "mode": "plan",
  "yoloModeToggled": false,
  "actModeApiProvider": "${CLINE_PROVIDER}",
  "planModeApiProvider": "${CLINE_PROVIDER}",
  "actModeApiModelId": "${CLINE_MODEL}",
  "planModeApiModelId": "${CLINE_MODEL}",
  "autoApprovalSettings": {
    "version": 3,
    "enabled": false,
    "favorites": [],
    "maxRequests": 0,
    "enableNotifications": false,
    "actions": {
      "readFiles": false,
      "readFilesExternally": false,
      "editFiles": false,
      "editFilesExternally": false,
      "executeSafeCommands": false,
      "executeAllCommands": false,
      "useBrowser": false,
      "useMcp": false
    }
  }
}
EOF

# Older releases placed raw API/OAuth values in this model-runtime carrier.
# Keep a stable empty tombstone so a persistent volume cannot resurrect them.
printf '{}\n' > "${CLINE_DATA_DIR}/secrets.json"

# Model-selected MCP execution remains disabled with unattended CLI execution.
cat > "${CLINE_HOME_DIR}/mcp_settings.json" <<'EOF'
{
  "mcpServers": {}
}
EOF
cp "${CLINE_HOME_DIR}/mcp_settings.json" "${CLINE_HOME_DIR}/data/settings/cline_mcp_settings.json"

# Tombstone a helper generated by older releases. Direct use fails explicitly even
# if a stale wrapper attempts to invoke it.
cat > "${CLINE_HOME_DIR}/ensure-model-config.sh" <<'EOF'
#!/bin/sh
echo "Unattended Cline execution is disabled pending an audited OSHAL broker." >&2
exit 73
EOF
chmod 700 "${CLINE_HOME_DIR}/ensure-model-config.sh"

echo "[setup-cline-auth] Wrote non-secret plan-only compatibility state; unattended CLI execution remains disabled."
