# swarm-cli — PowerShell command-line tab completion
# Generated by:  swarm-cli completion powershell
#
# Enable for the current session:
#   swarm-cli completion powershell | Out-String | Invoke-Expression
# Persist across sessions (add the line above to your profile):
#   if (!(Test-Path $PROFILE)) { New-Item -ItemType File -Path $PROFILE -Force | Out-Null }
#   'swarm-cli completion powershell | Out-String | Invoke-Expression' | Add-Content $PROFILE

Register-ArgumentCompleter -Native -CommandName @('swarm-cli','swarm-cli.cmd','swarm-cli.exe','swarm-cli.ps1') -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $commands = [ordered]@{
        login      = 'Sign in: mint a personal access token and save a context'
        logout     = "Forget the current context's stored credentials"
        whoami     = 'Show the server-resolved identity'
        ask        = 'One-shot question; the answer prints to stdout'
        chat       = 'Interactive REPL on a persistent Jarvis thread'
        history    = 'Print the current thread transcript'
        catalog    = 'List the apps/agents Jarvis can reach'
        tasks      = 'List durable handed-off work items and their results'
        tokens     = 'List or revoke personal access tokens'
        completion = 'Print a shell-completion script (bash|zsh|powershell)'
        version    = 'Print the swarm-cli version'
        help       = 'Show usage'
    }

    $flags = [ordered]@{
        '--url'       = 'Controller base URL (env OSHAL_API_URL)'
        '--token'     = 'Personal access token (env OSHAL_CLI_TOKEN)'
        '--secret'    = 'Trusted-service secret (bootstrap only)'
        '--sub'       = 'User sub to act as (required with --secret)'
        '--context'   = 'Named context to use'
        '--label'     = 'Token label for login / mint'
        '--session'   = 'Thread id'
        '--new'       = 'Start a fresh thread'
        '--json'      = 'Machine output: full result JSON on stdout'
        '--timeout'   = 'Max seconds to wait for an answer'
        '--poll'      = 'Poll interval in milliseconds'
        '--quiet'     = 'Suppress stderr status notes'
        '--no-banner' = 'Suppress the startup banner'
        '--version'   = 'Print the swarm-cli version'
        '--help'      = 'Show help and exit'
    }

    # Flags that consume the following token as their value.
    $valueFlags = @('--url','--token','--secret','--sub','--context','--label','--session','--timeout','--poll')
    $shells     = @('bash','zsh','powershell')

    $pv = [System.Management.Automation.CompletionResultType]::ParameterValue
    $pn = [System.Management.Automation.CompletionResultType]::ParameterName

    # Rebuild the committed argument list: everything after the program name,
    # minus the partial word the cursor is currently on.
    $tokens = @($commandAst.CommandElements | Select-Object -Skip 1 | ForEach-Object { $_.ToString() })
    if ($wordToComplete -and $tokens.Count -gt 0 -and $tokens[-1] -eq $wordToComplete) {
        if ($tokens.Count -eq 1) { $tokens = @() }
        else { $tokens = @($tokens[0..($tokens.Count - 2)]) }
    }
    $prev = if ($tokens.Count -gt 0) { $tokens[-1] } else { '' }

    $newResult = {
        param($text, $tip, $type)
        [System.Management.Automation.CompletionResult]::new($text, $text, $type, $tip)
    }
    $matchWord = { param($s) $s.StartsWith($wordToComplete, [System.StringComparison]::OrdinalIgnoreCase) }

    # 1) Completing the VALUE of a value-flag. Offer saved context names for --context;
    #    other values (URLs, tokens, secrets, ids) are free-form, so stay silent.
    if ($valueFlags -contains $prev) {
        if ($prev -eq '--context') {
            $stateDir = if ($env:OSHAL_CLI_STATE_DIR) { $env:OSHAL_CLI_STATE_DIR } else { Join-Path $HOME '.oshal' }
            $configPath = Join-Path $stateDir 'config.json'
            if (Test-Path $configPath) {
                try {
                    $cfg = Get-Content -Raw -LiteralPath $configPath | ConvertFrom-Json
                    if ($cfg.contexts) {
                        foreach ($name in $cfg.contexts.PSObject.Properties.Name) {
                            if (& $matchWord $name) { & $newResult $name 'Saved context' $pv }
                        }
                    }
                } catch { }
            }
        }
        return
    }

    # 2) A dash-word anywhere on the line -> offer the global flags.
    if ($wordToComplete -like '-*') {
        foreach ($f in $flags.Keys) {
            if (& $matchWord $f) { & $newResult $f $flags[$f] $pn }
        }
        return
    }

    # 3) Find the subcommand (first non-flag token) and any positional args after it.
    $subcommand  = $null
    $positionals = New-Object System.Collections.Generic.List[string]
    $expectValue = $false
    $seenSub     = $false
    foreach ($t in $tokens) {
        if ($expectValue) { $expectValue = $false; continue }
        if ($t -like '--*') {
            if ($valueFlags -contains $t) { $expectValue = $true }
            continue
        }
        if (-not $seenSub) { $subcommand = $t; $seenSub = $true; continue }
        $positionals.Add($t)
    }

    # 4) No subcommand chosen yet -> complete the subcommand name.
    if (-not $subcommand) {
        foreach ($c in $commands.Keys) {
            if (& $matchWord $c) { & $newResult $c $commands[$c] $pv }
        }
        return
    }

    # 5) Subcommand-specific positional arguments.
    switch ($subcommand) {
        'completion' {
            if ($positionals.Count -eq 0) {
                foreach ($s in $shells) {
                    if (& $matchWord $s) { & $newResult $s 'Shell to emit a completion script for' $pv }
                }
            }
            return
        }
        'tokens' {
            if ($positionals.Count -eq 0 -and (& $matchWord 'revoke')) {
                & $newResult 'revoke' 'Revoke a personal access token by id' $pv
            }
            return
        }
        default { return }
    }
}
