/**
 * CHANGE LOG
 * 1 | maintainer@emeraldcoastsystemsgroup.com | Exercise real Git archives, the store compiler and TypeScript; prove dishonest ambient types fail and dirty checkouts remain byte-identical. No compiler or filesystem doubles.
 */
import { describe, expect, it } from 'vitest';
import { execFileSync, spawn, spawnSync } from 'node:child_process';
import { copyFileSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, rmSync, unlinkSync, writeFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { tmpdir } from 'node:os';

const root = process.cwd();
const runner = join(root, 'scripts/check-store-compatibility.mjs');

/** @description Write a test file, creating parents as needed. */
function put(path: string, body: string) {
  mkdirSync(join(path, '..'), { recursive: true });
  writeFileSync(path, body);
}

/** @description Invoke real Git with isolated fixture identity and no hooks. */
function git(repo: string, ...args: string[]) {
  return execFileSync('git', ['-c', 'core.hooksPath=', '-c', 'core.autocrlf=false', '-c', 'user.name=Compatibility Test',
    '-c', 'user.email=compatibility@example.invalid', ...args], { cwd: repo, encoding: 'utf8', windowsHide: true }).trim();
}

/** @description Commit only the explicitly created fixture files in a disposable repository. */
function commit(repo: string) {
  git(repo, 'add', '.');
  git(repo, 'commit', '-qm', 'compatibility fixture');
  return git(repo, 'rev-parse', 'HEAD');
}

/** @description Construct small real repositories using the shipped store rebuild and installed TypeScript. */
function fixture() {
  const temp = mkdtempSync(join(tmpdir(), 'compatibility-test-'));
  const core = join(temp, 'core');
  const store = join(temp, 'store');
  mkdirSync(core); mkdirSync(store);
  git(core, 'init', '-q'); git(store, 'init', '-q');
  for (const file of ['package.json', 'package-lock.json']) copyFileSync(join(root, file), join(core, file));
  put(join(core, 'tsconfig.json'), JSON.stringify({ compilerOptions: {
    target: 'ES2022', module: 'commonjs', rootDir: 'src', baseUrl: '.', paths: { '@/*': ['src/*'] },
    strict: true, skipLibCheck: true, types: [],
  }, include: ['src/**/*.ts'] }));
  put(join(core, 'src/shared/workspace-root.ts'), 'export const workspaceRoot = "fixture";\n');
  const sourceStore = resolve(process.env.OSHAL_STORE_REPO ?? join(root, '..', 'oshal-applications'));
  for (const file of ['rebuild-store-routes.mjs', 'check-store-security.mjs']) {
    put(join(store, 'scripts/security', file), readFileSync(join(sourceStore, 'scripts/security', file), 'utf8'));
  }
  put(join(store, 'alpha/oshal-app.yaml'), 'name: alpha\nroutes:\n  - module: routes/main.js\n    factory: createRoutes\n    mountPath: /api/alpha\n    auth: oidc\n');
  put(join(store, 'alpha/src-routes/main.ts'), "import { workspaceRoot } from '@/shared/workspace-root';\nexport function createRoutes() { return workspaceRoot; }\n");
  put(join(store, 'alpha/routes/main.js'), 'exports.original = true;\n');
  const coreSha = commit(core), storeSha = commit(store);
  const reports = join(temp, 'reports');
  const args = [runner, '--core', core, '--store', store, '--dependencies', root, '--reports', reports];
  return { temp, core, store, reports, args, coreSha, storeSha };
}

/** @description Read the unique durable report generated by a fixture run. */
function report(reports: string) {
  const directory = join(reports, readdirSync(reports)[0]);
  return JSON.parse(readFileSync(join(directory, 'result.json'), 'utf8'));
}

describe('committed store compatibility', () => {
  it('compiles pinned exports, rejects an invented ambient export, and preserves dirty and untracked bytes', () => {
    const f = fixture();
    try {
      put(join(f.core, 'src/shared/workspace-root.ts'), 'uncommitted invalid core');
      put(join(f.store, 'alpha/src-routes/main.ts'), 'uncommitted invalid store');
      put(join(f.core, 'src/untracked.ts'), 'untracked core');
      put(join(f.store, 'alpha/src-routes/untracked.ts'), 'untracked store');
      const before = [git(f.core, 'status', '--porcelain'), git(f.store, 'status', '--porcelain')];
      const result = spawnSync(process.execPath, [...f.args, '--prove-rejection'], { encoding: 'utf8', windowsHide: true, timeout: 90000 });
      expect(result.status, result.stdout + result.stderr).toBe(0);
      const evidence = report(f.reports);
      expect(evidence.coreSha).toBe(f.coreSha); expect(evidence.storeSha).toBe(f.storeSha);
      expect(evidence.rejectionProof).toContain('TS2305');
      expect(evidence.cleaned).toBe(true); expect(existsSync(evidence.scratch)).toBe(false);
      expect(readFileSync(join(evidence.directory, 'rejection.log'), 'utf8')).toContain('inventedCompatibilityExport');
      expect([git(f.core, 'status', '--porcelain'), git(f.store, 'status', '--porcelain')]).toEqual(before);
      expect(readFileSync(join(f.core, 'src/shared/workspace-root.ts'), 'utf8')).toBe('uncommitted invalid core');
      expect(readFileSync(join(f.store, 'alpha/src-routes/main.ts'), 'utf8')).toBe('uncommitted invalid store');
      expect(readFileSync(join(f.core, 'src/untracked.ts'), 'utf8')).toBe('untracked core');
      expect(readFileSync(join(f.store, 'alpha/src-routes/untracked.ts'), 'utf8')).toBe('untracked store');
      expect(readFileSync(join(f.store, 'alpha/routes/main.js'), 'utf8')).toBe('exports.original = true;\n');
      expect(existsSync(join(root, 'node_modules/typescript/bin/tsc'))).toBe(true);
    } finally { rmSync(f.temp, { recursive: true, force: true }); }
  }, 120000);

  it('fails a committed bad import with package-specific diagnostics and keeps both repos untouched', () => {
    const f = fixture();
    try {
      put(join(f.store, 'alpha/src-routes/main.ts'), "import { inventedCompatibilityExport } from '@/shared/workspace-root';\nexport function createRoutes() { return inventedCompatibilityExport; }\n");
      put(join(f.store, 'alpha/src-routes/core-modules.d.ts'), "declare module '@/shared/workspace-root' { export const inventedCompatibilityExport: number; }\n");
      commit(f.store);
      const result = spawnSync(process.execPath, f.args, { encoding: 'utf8', windowsHide: true, timeout: 90000 });
      expect(result.status).toBe(1);
      const evidence = report(f.reports);
      expect(evidence.status).toBe('failed'); expect(evidence.cleaned).toBe(true);
      expect(readFileSync(join(evidence.directory, 'compile.log'), 'utf8').replaceAll('\\', '/')).toMatch(/alpha\/main.ts.*TS2305/);
      expect(git(f.core, 'status', '--porcelain')).toBe(''); expect(git(f.store, 'status', '--porcelain')).toBe('');
      expect(existsSync(evidence.scratch)).toBe(false);
    } finally { rmSync(f.temp, { recursive: true, force: true }); }
  }, 120000);

  it('refuses dependency reuse when the pinned lock differs', () => {
    const f = fixture();
    try {
      put(join(f.core, 'package-lock.json'), '{}\n'); commit(f.core);
      const result = spawnSync(process.execPath, f.args, { encoding: 'utf8', windowsHide: true, timeout: 30000 });
      expect(result.status).toBe(1);
      expect(report(f.reports).error).toContain('package-lock.json differs');
      expect(report(f.reports).cleaned).toBe(true);
    } finally { rmSync(f.temp, { recursive: true, force: true }); }
  }, 45000);

  it('keeps source repositories untouched when the compile process tree is forcibly interrupted', async () => {
    const f = fixture();
    let scratch: string | undefined;
    const child = spawn(process.execPath, f.args, { stdio: 'ignore', windowsHide: true, detached: process.platform !== 'win32' });
    const exited = new Promise((accept) => child.once('exit', accept));
    try {
      const deadline = Date.now() + 20000;
      while (Date.now() < deadline) {
        if (existsSync(f.reports) && readdirSync(f.reports).length) {
          const file = join(f.reports, readdirSync(f.reports)[0], 'result.json');
          if (existsSync(file)) {
            const evidence = report(f.reports);
            if (evidence.phase === 'compiling') { scratch = evidence.scratch; break; }
          }
        }
        await new Promise((accept) => setTimeout(accept, 20));
      }
      expect(scratch).toBeTruthy();
      // taskkill may report a missing parent after killing its compiler child: the parent's
      // error handling can exit before taskkill reaches it. The observed exit proves interruption.
      if (process.platform === 'win32') spawnSync('taskkill', ['/PID', String(child.pid), '/T', '/F'], { stdio: 'ignore', windowsHide: true });
      else process.kill(-child.pid!, 'SIGKILL');
      await exited;
      expect(child.exitCode).not.toBe(0);
      expect(git(f.core, 'status', '--porcelain')).toBe('');
      expect(git(f.store, 'status', '--porcelain')).toBe('');
      expect(readFileSync(join(f.store, 'alpha/routes/main.js'), 'utf8')).toBe('exports.original = true;\n');
      expect(existsSync(join(root, 'node_modules/typescript/bin/tsc'))).toBe(true);
    } finally {
      if (child.exitCode === null && child.signalCode === null) child.kill();
      if (scratch && existsSync(scratch)) {
        const link = join(scratch, 'core/node_modules');
        if (existsSync(link)) unlinkSync(link);
        rmSync(scratch, { recursive: true, force: true });
      }
      rmSync(f.temp, { recursive: true, force: true });
    }
  }, 30000);
});
